Feature/institutional storage quota restrict
RCOSDP/RDM-osf.io pull request #102
Opened 2019-06-10 10:13 UTC by rdm-dev02

## Purpose
ディスク容量のクォータ機能をPRいたします。

対応するフィーチャーは以下になります。
　【フィーチャー】機関で使用するストレージを指定する（#9815）
　【フィーチャー】クォータ制限を超えたファイル登録を抑止する（#9826）
　【フィーチャー】機関のデフォルトストレージにおけるクォータを管理する（#9825）

## Changes
## QA Notes
## Documentation
　RCOSDP/RDM-waterbutler/commits/feature/quota-restrict_staging
　もあわせてデプロイしてください。
　その際、機能を動作させるためには 、RDM-osf.io 側の .docker-compose.wb.env
　ファイル の OSF_URL 変数を利用できるようにする必要があります。

## Side Effects
## Ticket
　GRDM#9815, GRDM#9826, GRDM#9825

2019-06-13 06:27 UTC, hide24 requested changes
詳細については各コメントを参照ください。
あと、GoogleDriveについてアクセストークンを取得するUIが仕様に含まれていたはずですが実装を見付けることができませんでした。
納品文書にも記載を見付けられませんでした。
どのあたりを参照すればよいですか？

2019-06-13 06:27 UTC, hide24 commented on website/util/quota.py
> +    files_ids = list(map(lambda f: f.id, files))
djangoのORMの実装には詳しくないのですが、このアクセスは展開されるオブジェクト数(≒ヒープの消費量)的に安全と言えるのでしょうか？
ファイル数は割と簡単に発散するので危険が大きいように感じます。
こうした用向にはModel.objects.values_listメソッドが適切だと思います。

2019-06-13 06:27 UTC, hide24 commented on website/util/quota.py
> +def abbreviate_size(size):
小数点以下の表示桁数を2桁に丸めてください。
3桁目のroundでよいです。

2019-06-13 06:27 UTC, hide24 commented on website/util/quota.py
> +        user_quota.save()
FileInfoオブジェクトの更新(または削除)は必要ありませんか？

2019-06-13 06:27 UTC, hide24 commented on website/util/quota.py
> +    if file_size < 0:
この判定は適切ですか？
ファイルサイズに0未満の値が戻るのはどのような状況でしょう？
集計対象外とするなら、既存の値があればそれを減算する処理があるべきだと思います。

2019-06-13 06:27 UTC, hide24 commented on website/views.py
>      default_region = {'name': default_region.name, '_id': default_region._id}
同名の変数への再代入は避けるべきです

2019-06-13 06:27 UTC, hide24 commented on website/views.py
> +    institution_id = user.affiliated_institutions.first()
戻り値はオブジェクトでidそのものではないので、名前が不適切です

2019-06-13 06:27 UTC, hide24 commented on website/project/views/quota.py
> +        'max': max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3,
"api_settings.DEFAULT_SIZE_UNIT ** 3" に相当する値をapi_settingsの定数として定義しておくべき

2019-06-13 06:27 UTC, hide24 commented on website/project/views/node.py
> +        ret['isCustomStorageLocation'] = False if projectStorageType.storage_type == 1 else True
この"1"の意味を表明する定数はないのでしょうか？
おそらく ProjectStorageType.NII_STORAGE の事だと思いますが。

2019-06-13 06:27 UTC, hide24 commented on website/project/views/node.py
> +            'max_quota': max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3,
使用量と上限設定値の桁が違うというのはインターフェイスの設計としてまずくないでしょうか？
あと、"api_settings.DEFAULT_SIZE_UNIT ** 3"はそれを示す定数であるべきです。

2019-06-13 06:27 UTC, hide24 commented on website/templates/profile.mako
> +            Usage of ${ 'NII' if profile['quota']['storage_type'] == 1 else 'Institutional' } storage<br />
この"1"の意味を示す定数は定義されていないのでしょうか？
おそらく ProjectStorageType.NII_STORAGE の事だと思いますが。

2019-06-13 06:27 UTC, hide24 commented on website/profile/utils.py
> +        used_rate = float(used_quota) / (max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3)
使用量と上限設定値の桁が違うというのはインターフェイスの設計としてまずくないでしょうか？
あと、"api_settings.DEFAULT_SIZE_UNIT ** 3"はそれを示す定数であるべきです。

2019-06-13 06:27 UTC, hide24 commented on website/profile/utils.py
> +        elif used_rate <= 1:
動作に変化はないのですが、'1,0'か、上限であることを示す定数との比較にした方が宣言的で理解しやすいです。
あと、100%はerror表示にしてください。

2019-06-13 06:27 UTC, hide24 commented on scripts/refresh_addon_tokens.py
> +    dry_run = False
これはプロダクションコードとして残っていて良い記述ですか？

2019-06-13 06:27 UTC, hide24 commented on .docker-compose.wb.env
> +OSF_URL=http://192.168.168.167:5000
追加のパラメータのようですが、パラメータシートに記載がありません。
これはデプロイ先の環境依存で書き換える必要のある値でしょうか？

2019-06-13 06:27 UTC, hide24 commented on addons/base/views.py
> +        if payload.get('provider', None) != 'osfstorage':
ここのif文を分割した意図は何でしょうか？
ロジックの変更は皆無なのに大量のdiffが発生してしまっています。
今後のCOS最新版のマージの障害にもなるので、意味が無いなら元に戻してください。

2019-06-13 06:27 UTC, hide24 commented on admin/base/urls.py
> +            url(r'^customstoragelocation/', include('admin.rdm_custom_storage_location.urls', namespace='customstoragelocation')),
COSの開発部分では複数の単語からなるパスはsnake caseで統一されているようなので、'custom_storage_location'の使用を推奨します。

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +    permission_required = None
この設定は正しいですか？

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +            self.request.user.affiliated_institutions.all().count() > 0
同じ文脈の他の権限確認と記述が異なるようです。(L331など)
動作に影響はありませんが、統一しておくことを推奨します。

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +    def custom_size_abbreviation(self, size, abbr):
website/util/quota.py に同様のヘルパが実装されていますが、ここで再実装している意図は何でしょう？

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +    def custom_size_abbreviation(self, size, abbr):
website/util/quota.py に同様のヘルパが実装されていますが、ここで再実装している意図は何でしょう？

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +            max_quota_bytes = max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3
'api_settings.DEFAULT_SIZE_UNIT ** 3' を意味する定数を定義してください。

2019-06-13 06:27 UTC, hide24 commented on website/util/quota.py
> +def get_quota_info(user, storage_type=UserQuota.NII_STORAGE):
APIの仕様として使用量上限と実使用量の値の単位が異なるのはおかしいのではないでしょうか？

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +                max_quota_bytes = max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3
'api_settings.DEFAULT_SIZE_UNIT ** 3' を意味する定数を定義してください。

2019-06-13 06:27 UTC, hide24 commented on admin/institutions/views.py
> +        direction = self.request.GET.get('status', 'desc')
パラメータ名が適切でないように感じます。
直感的にはorder_byパラメータに'属性名_評価順'ぐらいで入って欲しいですが
現状ままの独立したパラメータでも良いです。
その場合の名前は素直に'direction'でしょうか。

2019-06-13 06:27 UTC, hide24 commented on admin/quota_recalc/views.py
> +def all_users(request, **kwargs):
計算量が桁違いに大きいアクションのように感じますが、アクセス制御は不要ですか？
タイムアウト対策もできていますか？

2019-06-13 06:27 UTC, hide24 commented on admin/rdm_custom_storage_location/cron.sh
> +*/30 * * * * curl http://localhost:8001/customstoragelocation/external_acc_update/d610ef95f0b0f5868f13919b8ed64070b9acb9c19b8da9f2c514ed938203ec3e236c9cad4f4146bdf22b4e79cf0d92f6d4f4c996d236c6b0ee79a
何かのトークンが埋められているようですが、何の値でしょうか？
パラメータシートにも記載がないようです。

2019-06-13 06:27 UTC, hide24 commented on admin/rdm_custom_storage_location/views.py
> +SITE_KEY = 'rdm_custom_storage_location'
アクセスキーの設定はアプリケーションのconfigに集約してください。
また、パラメータシートに記載がありません。

2019-06-13 06:27 UTC, hide24 commented on api/base/settings/defaults.py
> +DEFAULT_SIZE_UNIT = 1000
何のことだか判らない名称になっています。
SI接頭辞の基数が(10^3)か(2^10)かを保持しておく定数ということで良いのでしょうか？
そうであれば、素直に'BASE_FOR_METRIC_PREFIX'などにした方が良いと思います。
あと、システム中でGBを特別に扱うのであれば、その換算に使用する基数(10^9)を定数として定義してください。

2019-06-13 06:27 UTC, hide24 commented on api/nodes/serializers.py
> +        return float(used_quota) / (max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3)
'api_settings.DEFAULT_SIZE_UNIT ** 3' は定数であるべき

2019-06-13 06:27 UTC, hide24 commented on osf/models/node.py
> +    storage_type = 2
magic numberを埋めないでください

2019-06-13 06:27 UTC, hide24 commented on osf/models/node.py
> +        if nodeSettings.region_id == 1:
magic numberを埋めないでください

2019-06-13 06:27 UTC, hide24 commented on osf/models/node.py
> +            storage_type = 1
magic numberを埋めないでください

2019-06-17 05:50 UTC, tiida1120 commented on admin/institutions/views.py
> +class UserListByInstitutionID(PermissionRequiredMixin, ListView):
「UserListByInstitutionID」と「StatisticalStatusDefaultStorage」において、
　全く同じ処理があるので、共通化する方が良いかと思われます。
　例：custom_size_abbreviationメソッド、get_querysetメソッド内でuser_listにappendしている値など

2019-06-17 06:08 UTC, tiida1120 requested changes
コメントを追加しました。
詳細については下記をご確認ください。

2019-06-17 06:08 UTC, tiida1120 commented on admin/institutions/views.py
> +class UserListByInstitutionID(PermissionRequiredMixin, ListView):
「UserListByInstitutionID」と「StatisticalStatusDefaultStorage」において、
　全く同じ処理があるので、共通化する方が良いかと思われます。
　例：custom_size_abbreviationメソッド、get_querysetメソッド内でuser_listにappendしている値など

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
インラインでスタイルを指定していますが、外部css（institutions.css）への切り出しを。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
インラインでスタイルを指定していますが、外部css（institutions.css）への切り出しを。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
インラインでスタイルを指定していますが、外部css（institutions.css）への切り出しを。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
インラインでスタイルを指定していますが、外部css（institutions.css）への切り出しを。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
インラインでスタイルを指定していますが、外部css（institutions.css）への切り出しを。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/default_storage.html
> +        </div>
68~69行目に空のdivタグが残っています。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/statistical_status_default_storage_user.html
> +                </script>
14行目~21行目にかけて、javascriptが記載されていますが、外部jsに切り出して、共通化できるかと。

2019-06-17 06:08 UTC, tiida1120 commented on admin/templates/institutions/user_list_by_institute.html
> +                </script>
14行目~21行目にかけて、javascriptが記載されていますが、外部jsに切り出して、共通化できるかと。

2019-06-17 06:08 UTC, tiida1120 commented on admin/users/views.py
> +        return redirect(reverse_user(uid))
UserInstitutionQuotaViewのpostメソッドとほぼ同じ処理が使い回されています。
userとmax_quotaを返すメソッドを用意するのはどうでしょうか。

2019-06-17 06:08 UTC, tiida1120 commented on osf/models/user_quota.py
> +    )
「project_storage_type.py」に名称と値が同じ定数があります。
「project_storage_type.py」に定義されている値を使うか、名称を変更すべきかと。

2019-06-17 06:08 UTC, tiida1120 commented on osf_tests/test_node.py
> +        assert fetch_newly_created_project.storage_type == 2
「assert fetch_newly_created_project.storage_type != 1」と
 「assert fetch_newly_created_project.storage_type == 2」について、
 「project_storage_type.py」にある定数を使って判定すべきかと。

2019-06-18 00:37 UTC, rdm-dev08 commented on website/util/quota.py
> +    files_ids = list(map(lambda f: f.id, files))
30d05650091c620e60d98a8a7cc766ab61aad8c9

2019-06-18 00:38 UTC, rdm-dev08 commented on website/views.py
>      default_region = {'name': default_region.name, '_id': default_region._id}
3fdcd3bb213d8d81c8578a915851e703766fe6af

2019-06-18 00:39 UTC, rdm-dev08 commented on website/views.py
> +    institution_id = user.affiliated_institutions.first()
487d41e71539249441663e3b4e2d47eedd3fbf50

2019-06-18 00:40 UTC, rdm-dev08 commented on website/project/views/quota.py
> +        'max': max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3,
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:41 UTC, rdm-dev08 commented on website/project/views/node.py
> +            'max_quota': max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3,
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:41 UTC, rdm-dev08 commented on website/profile/utils.py
> +        used_rate = float(used_quota) / (max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3)
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:41 UTC, rdm-dev08 commented on admin/institutions/views.py
> +            max_quota_bytes = max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:41 UTC, rdm-dev08 commented on admin/institutions/views.py
> +                max_quota_bytes = max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:42 UTC, rdm-dev08 commented on api/nodes/serializers.py
> +        return float(used_quota) / (max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3)
6270c5fe44563f76cd46463e5987af81f6290fed

2019-06-18 00:43 UTC, rdm-dev08 commented on website/project/views/node.py
> +        ret['isCustomStorageLocation'] = False if projectStorageType.storage_type == 1 else True
9436825319667370c426af4a27310a62602ec5ee

2019-06-18 00:44 UTC, rdm-dev08 commented on website/templates/profile.mako
> +            Usage of ${ 'NII' if profile['quota']['storage_type'] == 1 else 'Institutional' } storage<br />
9436825319667370c426af4a27310a62602ec5ee

2019-06-18 00:44 UTC, rdm-dev08 commented on website/profile/utils.py
> +        elif used_rate <= 1:
96997380dff80ac1c3a892230a420ced75091ea7

2019-06-18 00:45 UTC, rdm-dev08 commented on scripts/refresh_addon_tokens.py
> +    dry_run = False
b9faad38090995c2ae1402b85af412aba91a8dc0

2019-06-18 00:48 UTC, rdm-dev08 commented on addons/base/views.py
> +        if payload.get('provider', None) != 'osfstorage':
3429f00cb783b31931f3244b4e4c1a482b4f3ccd

2019-06-18 01:00 UTC, rdm-dev08 commented on admin/base/urls.py
> +            url(r'^customstoragelocation/', include('admin.rdm_custom_storage_location.urls', namespace='customstoragelocation')),
aeea939fcc04b1afbbce63e57e1cb0e94300b866

2019-06-18 01:00 UTC, rdm-dev08 commented on admin/institutions/views.py
> +    permission_required = None
d99bb9f512ffb11755d0a976e5cfc7d117f42ab6

2019-06-18 01:01 UTC, rdm-dev08 commented on admin/institutions/views.py
> +            self.request.user.affiliated_institutions.all().count() > 0
37a50282b70c301e7c037de8d849d565e2f1056a

2019-06-18 01:02 UTC, rdm-dev08 commented on api/base/settings/defaults.py
> +DEFAULT_SIZE_UNIT = 1000
6e705779ed7a4dbab2ababa18428d7c8a0f382eb

2019-06-18 01:03 UTC, rdm-dev08 commented on osf/models/node.py
> +    storage_type = 2
14ba3fe9993d080792bc448d5002ea1174d7bb98

2019-06-18 01:03 UTC, rdm-dev08 commented on osf/models/node.py
> +        if nodeSettings.region_id == 1:
14ba3fe9993d080792bc448d5002ea1174d7bb98

2019-06-18 01:03 UTC, rdm-dev08 commented on osf/models/node.py
> +            storage_type = 1
14ba3fe9993d080792bc448d5002ea1174d7bb98

2019-06-18 01:40 UTC, rdm-dev02 commented on website/util/quota.py
> +def abbreviate_size(size):
この関数は表示のためではなく、計算するために使用しています。
roundは表示側でしています。
(現在、小数点以下1桁に丸めて表示しています。全ての画面で表示桁数を2桁に修正すべきというご指摘と受け取ればよいでしょうか。)

2019-06-18 01:42 UTC, rdm-dev02 commented on website/util/quota.py
> +        user_quota.save()
更新は以下で実装済みです。
https://github.com/RCOSDP/RDM-osf.io/blob/feature/inst-sto_quota-restrict_staging/website/util/quota.py#L147-L148

FileInfo は BaseFileNode を拡張しているため、削除したら BaseFileNode に削除フラグが立ちます。現在の実装はこれを当てにしています。
OSF はよく項目を削除しないで、フラグを使っていますので、この実装も同じパターンを従うべきだと考えました。ですので、FileInfo 項目の削除は不要と思いますがいかがでしょうか。

2019-06-18 01:45 UTC, rdm-dev02 commented on website/util/quota.py
> +    if file_size < 0:
悪意を持った人が API に直接リクエストを投げて、使用中のクオータを減らそうとしている場合の対策になります。あくまでもセキュリティ的な観点のためで、普段は起きない処理です。

2019-06-18 02:17 UTC, rdm-dev02 commented on website/project/views/node.py
> +            'max_quota': max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3,
桁については画面表示をご確認いただいて進めていたのでそこまで深掘りしておりませんでした。
ここでは同じ単位のバイトに揃えています。max_quotaについて、別のご指摘でいただいていたように小数点以下の桁数を2桁で管理するように直すべきでしょうか？

後半のご指摘の定数については修正いたしました。

2019-06-18 02:17 UTC, rdm-dev02 commented on website/profile/utils.py
> +        used_rate = float(used_quota) / (max_quota * api_settings.DEFAULT_SIZE_UNIT ** 3)
桁については画面表示をご確認いただいて進めていたのでそこまで深掘りしておりませんでした。
ここでは同じ単位のバイトに揃えています。max_quotaについて、別のご指摘でいただいていたように小数点以下の桁数を2桁で管理するように直すべきでしょうか？

後半のご指摘の定数については修正いたしました。

2019-06-18 02:18 UTC, rdm-dev02 commented on .docker-compose.wb.env
> +OSF_URL=http://192.168.168.167:5000
はい。Redmine上のパラメータシートには先日反映しております。

2019-06-18 02:23 UTC, rdm-dev02 commented on admin/institutions/views.py
> +    def custom_size_abbreviation(self, size, abbr):
Admin側でバイト単位は表示せず、最小単位はKBという仕様から、274, 275行目でquota.abbreviate_sizeのリターン値を使用して、ByteをKBに変更しています。
（再実装という感覚ではないです。）
この関数はサイズが < 1000 bytes だったら、 KB にしています。

2019-06-18 02:25 UTC, rdm-dev02 commented on admin/institutions/views.py
> +    def custom_size_abbreviation(self, size, abbr):
Admin側でバイト単位は表示せず、最小単位はKBという仕様から、274, 275行目でquota.abbreviate_sizeのリターン値を使用して、ByteをKBに変更しています。
※こちらは機関ストレージ向けの実装箇所です。

2019-06-18 02:37 UTC, rdm-dev02 commented on admin/institutions/views.py
> +        direction = self.request.GET.get('status', 'desc')
最初の実装では status ではなく direction だったのですが、既存のページング機能は direction のパラメータをサポートしていませんでした。
ページングは共通機能なので、変えない方がいいと判断し、direction を実装する代わりに、status パラメータを使用するようにしました。

2019-06-18 02:38 UTC, rdm-dev02 commented on admin/quota_recalc/views.py
> +def all_users(request, **kwargs):
curlコマンドによる統計のトリガとしての利用を想定しているので、ブラウザ等からのアクセスは想定していません。
このため、タイムアウトさせず、処理が終わるまで待つ想定となります。

統計処理（/rdm_statistics）の集計処理と同じく、システム内部からの実行を想定しており、
ファイヤーウォールなどによるアクセス制限を実施頂く想定です。

2019-06-18 02:47 UTC, rdm-dev02 commented on admin/rdm_custom_storage_location/cron.sh
> +*/30 * * * * curl http://localhost:8001/customstoragelocation/external_acc_update/d610ef95f0b0f5868f13919b8ed64070b9acb9c19b8da9f2c514ed938203ec3e236c9cad4f4146bdf22b4e79cf0d92f6d4f4c996d236c6b0ee79a
GoogleDriveのトークンリフレッシュの処理を定期実行する際に、外部から実行されないように、セキュリティのために入れたトークンです。

2019-06-18 02:50 UTC, rdm-dev02 commented on admin/rdm_custom_storage_location/views.py
> +SITE_KEY = 'rdm_custom_storage_location'
このキーの設定はこのページにしか使わない、セキュリティのために入れた値です。
configに集約する必要がありますでしょうか。また、念の為確認させていただきたいのですが、このconfigはどこを指しておりますでしょうか。

また、同様の実装を、rdm_statistics でも行っております。
https://github.com/RCOSDP/RDM-osf.io/blob/feature/inst-sto_quota-restrict_staging/admin/rdm_statistics/views.py#L54

2019-06-18 06:14 UTC, rdm-dev08 commented on admin/institutions/views.py
> +class UserListByInstitutionID(PermissionRequiredMixin, ListView):
a4f501f5a35f162e7f25c90db167226053f7b684

2019-06-18 07:11 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:11 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:11 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:11 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:11 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        <div class="row" style="margin-bottom: 15px;">
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:12 UTC, rdm-dev08 commented on admin/templates/institutions/default_storage.html
> +        </div>
98aa751002f66272e725d24953c30126ab97cd03

2019-06-18 07:12 UTC, rdm-dev08 commented on admin/templates/institutions/statistical_status_default_storage_user.html
> +                </script>
f68e865654337483510abe451dd7a06fdd66323f

2019-06-18 07:12 UTC, rdm-dev08 commented on admin/templates/institutions/user_list_by_institute.html
> +                </script>
f68e865654337483510abe451dd7a06fdd66323f

2019-06-18 08:42 UTC, rdm-dev08 commented on admin/users/views.py
> +        return redirect(reverse_user(uid))
88309e62937a42bc224fcd473b9ea38601f69993

2019-06-19 04:01 UTC, rdm-dev08 commented on osf/models/user_quota.py
> +    )
4d525432bed19ca003d5873ee63f689df14c6cde

2019-06-19 04:12 UTC, rdm-dev08 commented on osf_tests/test_node.py
> +        assert fetch_newly_created_project.storage_type == 2
e95298b0809207c2f1e2628b355ae1faebfadd79

2019-06-21 06:21 UTC, hide24 commented on website/util/quota.py
> +def abbreviate_size(size):
表示側で丸められているなら結構です。

2019-08-05 05:46 UTC, merged