Feature/i18n js 201912 n
RCOSDP/RDM-osf.io pull request #145
Opened 2019-12-19 04:56 UTC by west1636

<summary>
can switch words in RDM-osf.io display between ja / en.
<change files list>
(revise:6)
 package.json 
yarn.lock 
webpack.common.config.js 
website/static/js/myProjects.js 
website/static/js/osfLanguage.js 
website/static/js/projectSettings.js
(add:3) 
website/static/js/setLanguage.js
 website/static/js/translations/ja.json
 website/static/js/translations/en.json

that's all.

2019-12-19 07:08 UTC, hide24 requested changes
コメントを参照ください

2019-12-19 07:08 UTC, hide24 commented on website/static/js/myProjects.js
> +var gt = setLanguage.setLanguage();
setLanguageメソッドをgt(GetText?)変数で受けるのは良くない
どちらかの名称を変更すべき
名前重要

2019-12-19 07:08 UTC, hide24 commented on website/static/js/myProjects.js
> +                    m('small.hidden-xs', gt.gettext('Browse and organize all your projects'))
悪くはないけど、どこかで
var _ = function(msgid) { return gt.gettext(msgid); };
ぐらいの記述を入れておくと
m('small.hidden-xs', _('Browse and organize all your projects'))
で書けるはず。
複数のmsgidに対して翻訳を行なう場合の総タイプ数が減る。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/osfLanguage.js
> +            ja: 'プロジェクトの設定が更新されました。'
翻訳用の辞書を用意する場合の配慮として、
辞書ファイルにはmsgidとターゲットとなる言語のテキストのみにするべきであるというものがあります。
enとjaのリソースは可能なかぎり別ファイルに切り分けるべきですし、
データ構造としても言語コードはドメインより上位の分類であるべきです。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/projectSettings.js
> +                JSON.stringify(self.changeMessage(setLanguage.getOsfLanguage('projectSettings','updateSuccessMessage',browserLang), 'text-success'));
この処理はsetLanguage.jsかosfLanguage.js内のメソッドとしてラップするべきです。
想定されるインターフェイスはメソッドがt()として提供されるとして
self.changeMessage(t('projectSettings', 'updateSuccessMessage'), 'text-success');
このファイル内で共通のドメイン'projectSettings'をデフォルト値として設定できるインターフェイスがあると良いかも。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/projectSettings.js
> +var browserLang = setLanguage.getBrowserLang()
下の指摘とも関連しますが、このファイルがブラウザの言語を判別する必要はないかと思います。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/projectSettings.js
> +                JSON.stringify(self.changeMessage(setLanguage.getOsfLanguage('projectSettings','updateSuccessMessage',browserLang), 'text-success'));
同上

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +
トルツメ
以下でも同様ですが、余計な改行は打たないようにしましょう。
画面あたりの情報量が下がりすぎます。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +var langSetting = ['en','ja'];
Settingだと何の事だか判らないのでもっと具体的な名前をつけましょう。
おそらくこの場合はacceptLanguagesが適切
名前重要

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +        if(language == langSetting[i]){
正規表現マッチャを使用すれば国コードを含む'ja-JP'や'en-US''en-UK'もそれぞれ'ja''en'に同定できると思います。
var pattern = new RegExp(langSetting[i]);
if(language.match(pattern)) { 処理... }
ぐらいの感じ
正規表現パターンはもっと前で生成してlangSetting(acceptLanguage)との組で連想配列にしておくのが良いでしょう。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +            languageFlag = true;
名前重要
しかし、本質的に不要な変数。(次のコメントに続く)

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +    }
ここのフォールバック処理がやや冗長です。
まず、ブラウザ変数を受けるlanguage変数(仮称browserLanguage)と
戻り値として使用するlanguage変数(仮称selectedLanguage)を別の変数として定義します。

7行目あたりで selectedLanguage の初期値として defaultLanguage を設定しておきます。
var selectedLanguage = defaultLanguage;

16行目でlangSetting(acceptLanguage)内にbrowserLanguageと一致する値を見付けた場合に
selectedLanguage を browserLanguageと合致したlangSetting(acceptLanguage)の値で上書きします。
selectedLanguage = langSetting[i];
先の提案により正規表現マッチャを使用した場合、browserLanguageは'en-US'だったりする場合があるからね

あとは selectedLanguage  をreturnしてやれば、if文と内容の想像できない名前のついたlanguageFlag変数を取り除くことができます。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +    var Gettext = require('node-gettext');
requireを記述する際は他の変数定義より前に
requireの記述についても、外部のライブラリの参照 > ローカルファイルの参照 の順に並べてください。
また、node-gettextについてはこのjsファイルのトップレベルでグローバル変数に受けた方が良いと思います。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +    return gt;
別のファイルのコメントにも書きましたが、
setLanguageのメソッド名で戻り値がGettextオブジェクトというのはいただけません。
名前重要

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +
末尾の空白も無駄なdiffを生むもとなので、できる限り避ける

2019-12-19 07:08 UTC, hide24 commented on website/static/js/translations/en.json
> +}
ファイル末尾には改行を打つようにした方が良い
プロジェクトによって「必ず打つ」「打たない」の流派があるので、基本的には他のファイルにあわせること

2019-12-19 07:08 UTC, hide24 commented on website/static/js/setLanguage.js
> +}
別のファイルの指摘に書いたけど、これは文字列の収められたオブジェクトを返却するのではなく
ドメインとmsgidを引数に取り、ブラウザの言語設定などを参照して最終的に表示に使用する文字列を返却するメソッドとして実装されるべき
ドメインは参照されるファイルごとに固定である場合が多いので、デフォルト値を設定できるインターフェイスだとなお良い。

2019-12-19 07:08 UTC, hide24 commented on website/static/js/translations/ja.json
> +}
同上

2019-12-23 08:27 UTC, west1636 commented on website/static/js/myProjects.js
> +var gt = setLanguage.setLanguage();
setLanguage→rdmGettextへ変更しました。(合わせてsetLanguage.js→rdmGettext.jsへ変更)

2019-12-23 08:28 UTC, west1636 commented on website/static/js/myProjects.js
> +                    m('small.hidden-xs', gt.gettext('Browse and organize all your projects'))
上記対応完了しました。

2019-12-23 08:29 UTC, west1636 commented on website/static/js/osfLanguage.js
> +            ja: 'プロジェクトの設定が更新されました。'
osfLanguage_X.jsを作成しました。
・osfLanguage_en.js
・osfLanguage_ja.js

2019-12-23 08:33 UTC, west1636 commented on website/static/js/projectSettings.js
> +                JSON.stringify(self.changeMessage(setLanguage.getOsfLanguage('projectSettings','updateSuccessMessage',browserLang), 'text-success'));
デフォルト値をargumentsに設定するようにgetOsfLanguageを変更(また、関数名をgetOsfLanguage()をosfLanguage()へ変更)

2019-12-23 08:33 UTC, west1636 commented on website/static/js/projectSettings.js
> +var browserLang = setLanguage.getBrowserLang()
上記対応完了しました。

2019-12-23 08:33 UTC, west1636 commented on website/static/js/setLanguage.js
> +    return gt;
setLanguage→rdmGettextへ変更

2019-12-23 08:34 UTC, west1636 commented on website/static/js/setLanguage.js
> +
上記対応完了しました。

2019-12-23 08:34 UTC, west1636 commented on website/static/js/translations/en.json
> +}
上記対応完了しました。

2019-12-23 08:36 UTC, west1636 commented on website/static/js/setLanguage.js
> +}
projectSettings.js の指摘と同様に対応しました。
（デフォルト値をargumentsに設定するようにgetOsfLanguageを変更(また、関数名をgetOsfLanguage()をosfLanguage()へ変更)）

2019-12-23 08:36 UTC, west1636 commented on website/static/js/translations/ja.json
> +}
上記対応完了しました。

2020-03-10 05:01 UTC, closed without merging