dropboxbusiness
RCOSDP/RDM-osf.io pull request #146
Opened 2019-12-19 18:49 UTC by soum-takuya

## Purpose

new addon: dropboxbusiness
[GRDM-15573,15575,15576,15578,15579]

## Changes

## QA Notes

## Documentation

## Side Effects

## Ticket

[GRDM-15573,15575,15576,15578,15579]

2019-12-24 08:38 UTC, hide24 requested changes

2019-12-24 08:38 UTC, hide24 commented on addons/dropboxbusiness/settings/local-dist.py
> +DROPBOX_BUSINESS_MANAGE_SECRET = 'changeme'
defaults.pyに定義されている定数と名称が異なるようです。
デプロイ時に上書きされなくてちょっと悩んだので、defaults.pyの名前に揃えておいてください。

2019-12-24 08:47 UTC, soum-takuya commented on addons/dropboxbusiness/settings/local-dist.py
> +DROPBOX_BUSINESS_MANAGE_SECRET = 'changeme'
ご指摘ありがとうございます。お手数をおかけしました。
修正します。

チームフォルダー名の形式修正はあとで大丈夫ですか？
チケットを作って作業しようとは思っていますが、このプルリクに含めることも可能です。

2019-12-27 07:20 UTC, soum-takuya commented on addons/dropboxbusiness/settings/local-dist.py
> +DROPBOX_BUSINESS_MANAGE_SECRET = 'changeme'
local-dist.py を更新しました。

それと、Dropbox連携処理失敗時のチームフォルダー・グループの削除、ログメッセージの改善をおこないました。

2020-01-20 04:07 UTC, merged