Feature/i18n js 202001 n2
RCOSDP/RDM-osf.io pull request #154
Opened 2020-03-08 11:42 UTC by west1636

## Purpose

apply i18n(ja) to RDM-osf.io

## Changes

revise files mako,js,python,html and required setting files add pot, po, js, mako

(Mako)
--profile or templates-- 
・pot 
・po 
・mako files(including messages.mako) 
--setting files-- 
・dockerfile 
・framework/flask/__init__.py 
・framework/routing/__init__.py 
・requirements.txt 
・website/settings/babel.cfg 
・website/settings/defaults.py 
・addons/base/models.py 
・addons/base/apps.py 

(Javascript)
--profile or js-- 
・pot 
・po 
・js(including website/static/js/rdmGettext.js,js_messages.js,script/rdmPoToJson.js) 
--setting files-- 
・yarn.lock 
・package.json 
・webpack.common.config.js 
・website/settings/babel_js.cfg 

(Py)
--python code-- 
・py (admin) 

(HTML)
--html-- 
・html 
--setting files-- 
・admin/base/settings/defaults.py 
・admin/translations/ja/django.po (no pot file) 
・dockerfile

that's all.

2020-03-11 09:52 UTC, hide24 requested changes
総評としてはとても良い出来だと思います。
主な指摘内容としては、
・翻訳ファイル(potやpo)に出現するキーワード(変数名)のcaseについて
camelCaseとsnake_caseが混在しています。
主にhtmlのクラス名/IDやjavaScript中の変数名に由来するキーワードがcamelCase
python中の変数名に由来するキーワードがsnake_caseになっているという事情は理解できますが
翻訳ファイルを見る人には関係のない事情ですし、翻訳ファイルだけを見る人にはプロジェクトの統制が劣っているように見えてしまいます。
そのためどちらかに統一されるべきです。
既存の量的にcamelCaseの方が多いように感じるのでsnake_caseの箇所にコメントを入れています。(途中で飽きたので全部ではないです)
snake_caseの方が好みならそちらに統一しても良いです。
・JavaScript中でのgetText関連のrequire
各ファイルでgetText関連のライブラリをrequireする際に常に3行コピペされています。
rdmGettext.jsの側で_をexportしておけばrequrieの1行で足りると思います。
・JavaScript中でのsprintfライブラリの利用法について
`var sprintf = require('agh.sprintf').sprintf;`
とrequireすれば実際にsprintfを利用する際のagh.の接頭辞が不要になるはずです。
sprintfフォーマット中に置換される変数が1つしかない場合は序数を付与せず%sとした方が可読性が高いと思います。
また、agh.sprintfではなくnode.sprintfライブラリを利用すれば他の場所で利用しているような名前ベースの変数挿入ができるようです。
https://github.com/maritz/node-sprintf

2020-03-11 09:52 UTC, hide24 commented on Dockerfile
> +    && yarn cache clean \
原理的な間違いではないけど、挿入場所が比較的前(≒キャッシュが効かなくなるタイミングが早い)ので、コンテナのビルドに毎回必要以上の時間がかかっているはず。
もう少し後ろに挿入できないか検討する。

2020-03-11 09:52 UTC, hide24 commented on addons/gitlab/templates/gitlab_credentials_modal.mako
> +                                        ${_('(Get from GitLab <i %(classTag)s></i>)') % dict(classTag='class="fa fa-external-link-square"') | n}
キーワードclassTagの意図が読み辛いように感じるので名称の変更を提案します。
またこのIタグは外部リンクアイコンが描画されるはずなので、Iタグそのものをキーワード化した方が良いと思います。
`${_('Get from GitLab %(externalLinkIcon)s') % dict(externalLinkIcon='<i class="fa fa-external-link-square"></i>')}`
ぐらいの勢いでどうでしょう？

2020-03-11 09:52 UTC, hide24 commented on addons/bitbucket/templates/bitbucket_node_settings.mako
> +                <a href="%(addons_url)s">account settings page</a>.') % dict(addons_url=h(addons_url),addonName='Bitbucket') | n}
キーワードにcamelCaseとsnake_caseが混在しています。統一するようにしてください。
全般にcamelCaseの方が多いように見えるのでcamelCaseへの統一を提案します。

2020-03-11 09:52 UTC, hide24 commented on addons/bitbucket/templates/bitbucket_node_settings.mako
> +                may no longer be valid. Contact %(auth_osf_name)s to verify.') % dict(auth_osf_name=auth_osf_name,addonName='Bitbucket')}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/dataverse/templates/dataverse_credentials_modal.mako
> +                                        ${_('(Get from Dataverse %(dataverse_link)s)') % dict(dataverse_link='<i class="fa fa-external-link-square"></i>') | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/github/templates/github_node_settings.mako
> +                <a href="%(addons_url)s">account settings page</a>.') % dict(addons_url=h(addons_url),addonName='GitHub') | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/github/templates/github_node_settings.mako
> +                may no longer be valid. Contact %(auth_osf_name)s to verify.") % dict(auth_osf_name=auth_osf_name,addonName='GitHub')}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/gitlab/templates/gitlab_node_settings.mako
> +                    <a href="%(addons_url)s">account settings page</a>.') % dict(addons_url=h(addons_url),addonName='GitLab') | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/gitlab/templates/gitlab_node_settings.mako
> +                    may no longer be valid. Contact %(auth_osf_name)s to verify.') % dict(auth_osf_name=auth_osf_name,addonName='GitLab')}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/nextcloud/templates/nextcloud_credentials_modal.mako
> +                                <em> ${_('These credentials will be encrypted. However, we <strong>strongly encourage</strong> using a <a %(open_with_new_window)s> Device (or App) Password</a>.') % d
キーワードopen_with_new_windowはアプリケーションの動作についての記述で訳者に必要な情報を含んでいないように感じます。変更を提案。
切り出し範囲はそのままで、nextcloudManualUrlの名称を提案します。
(追記)ownCloudで同じメッセージがあるので、キーワード名はuserManualUrlぐらいに汎化した方が良いか？

2020-03-11 09:52 UTC, hide24 commented on addons/nextcloud/templates/nextcloud_user_settings.mako
> +                        <th class="text-muted default-authorized-by">${_('Authorized by %(user_name)s on %(profile_page)s') % dict(user_name='<em><span data-bind="text: name"></span></em>', profile_p
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/owncloud/templates/owncloud_credentials_modal.mako
> +                                    <em>${_('Only ownCloud instances supporting <a %(webdav_url)s>WebDAV</a> and <a %(ocs_url)s>\
caseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/owncloud/templates/owncloud_credentials_modal.mako
> +                                <em>${_(' These credentials will be encrypted. However, we <strong>strongly encourage</strong> using a <a %(open_with_new_window)s> Device (or App) Password</a>.') % d
nextCloudと同じ観点でキーワードopen_with_new_windowの名称変更を提案。
ownCloudManualUrlないし、メッセージIDの共通化を考慮するならuserManualUrl を提案。

2020-03-11 09:52 UTC, hide24 commented on addons/twofactor/static/twoFactorUserConfig.js
> +        message: _('Enabling two-factor authentication will not immediately activate this feature for your account. You will need to follow the steps that appear below to complete the activation of t
本質的な問題ではないのですが、ここの修正は
`       message: _('Enabling two-factor authentication will not immediately activate ' +
            'this feature for your account. You will need to follow the ' +
            'steps that appear below to complete the activation of two-factor authentication ' +
            'for your account.'),`
では駄目な理由があったのでしょうか？
極力diffが少なくなるような修正が望ましいかと思います。

2020-03-11 09:52 UTC, hide24 commented on addons/twofactor/templates/twofactor_user_settings.mako
> +        <a %(google_url)s>Android</a> and <a %(itunes_url)s>iOS</a>.') % dict(google_url='href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"',itunes_url='href
メッセージID中の行連結はクォートを一度閉じて+で明示的に連結した方が良い気がします。
また、google_url/itunes_urlのキーワードについてcaseの統一を含めた名称の変更を提案。google<>iTuensのサービスレベルの対応が的確でないように感じます。
`      <p>${_('To use, you must install an appropriate application on your mobile device. Google Authenticator is a popular choice and is available for both ' +
        '<a %(playStoreUrl)s>Android</a> and <a %(appStroreUrl)s>iOS</a>.') % dict(playStoreUrl='href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"',appStroreUrl='href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8"') | n}</p>`
ぐらいでどうでしょう？

2020-03-11 09:52 UTC, hide24 commented on addons/twofactor/templates/twofactor_user_settings.mako
> +        %(secret_key)s into your authentication device.') % dict(secret_key='<code data-bind="text: secret"></code>') | n}
行の分割とcaseの統一

2020-03-11 09:52 UTC, hide24 commented on addons/wiki/static/WikiEditor.js
> +        var clean1 = typeof wiki1 === 'string' ?
空白文字か改行コードが意図せず変更されている可能性があります。
この行がdiffに出力されないようにしてください。

2020-03-11 09:52 UTC, hide24 commented on addons/wiki/static/WikiEditor.js
> +        var clean2 = typeof wiki2 === 'string' ?
上のclean1についての行と同じ。意図していない変更を元に戻してください。

2020-03-11 09:52 UTC, hide24 commented on addons/wiki/static/WikiEditor.js
> +                _('the page now, those changes may be lost.');
`            return _('There are unsaved changes to your wiki. If you exit ' +`
`                'the page now, those changes may be lost.');`
一文なので1つのメッセージIDとして抽出されるべきです。

2020-03-11 09:52 UTC, hide24 commented on addons/wiki/static/pagedown-ace/Markdown.Editor.js
>      var defaultsStrings = {
コードの動作を追っていないのでこれで良いのか悪いのか判断できないのですが、
このオブジェクトの要素でメッセージIDが抽出されているものとされていないものがあるのは正しい判断なのでしょうか？

2020-03-11 09:52 UTC, hide24 commented on addons/wiki/templates/wiki-bar-modal-help.mako
> +                    ${_('The wiki uses the <a %(mark_url)s>Markdown</a> syntax. For more information and examples, go to our <a %(zendesk_url)s>Guides.</a>') % dict(mark_url='href="https://daringfire
caseの統一とキーワード名の再考を提案。
markdownSyntaxUrl と guideUrl ぐらい?
zendeskはカスタマサポート用のツールスイートで、ここでのリンク先はそのwiki機能で作成したページです。
zendeskの名前自体に訳者に有効な情報はありません。

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/dataverse/dataverseRdmConfig.js
> +                agh.sprintf(_('Are you sure you want to disconnect the Dataverse account on <strong>%1$s</strong>? This will revoke access to Dataverse for all projects associated with this account.'
特に意図がないなら %1$s → %s の方が事故りにくい気がしますがどうでしょう?

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/dataverse/dataverseRdmConfig.js
> +            Raven.captureMessage(agh.sprintf(_('Error while removing addon authorization for %1$s') , account.id), {
ここも %s にはできない?

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/rdm-addons-page.js
> +            message: agh.sprintf(_("Are you sure you want to disallow the %1$s?<br>"),$osf.htmlEscape(addonFullName)) +
メッセージIDは<BR>の前で切るべきだと思います。引数が一つだけなら位置指定子は省略した方が事故が少なくなると思います。

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/rdm-addons-page.js
> +                     agh.sprintf(_("This will revoke access to %1$s for all projects using the accounts.<br><br>"),$osf.htmlEscape(addonFullName)) +
メッセージIDは
の前で切るべきだと思います。引数が一つだけなら位置指定子は省略した方が事故が少なくなると思います。

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/rdm-addons-page.js
> +                     agh.sprintf(_("Type the following to continue: <strong>%1$s</strong><br><br>"),$osf.htmlEscape(deletionKey)) +
メッセージIDは
の前で切るべきだと思います。引数が一つだけなら位置指定子は省略した方が事故が少なくなると思います。

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/rdm-addons-page.js
> +                        $osf.growl('Verification failed', _('Strings did not match'));
'Verification failed' の方はメッセージIDとして抽出しなくてよい？

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_addons/s3/s3RdmConfig.js
> +            Raven.captureMessage(agh.sprintf(_('Error while removing addon authorization for %1$s') , account.id), {
パラメータが1つの時は～(略

2020-03-11 09:52 UTC, hide24 commented on admin/static/js/rdm_custom_storage_location/rdm-institutional-storage-page.js
> +            $osf.growl('Success', _('Institutional Storage set successfully'), 'success');
API的には第一引数はダイアログのタイトルに表示される(現在のスタイルでは見えないぽい)仕様のはずなので、最初の'Success'はメッセージIDを抽出しておいた方が良い気がします。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/banners/confirm_delete.html
> +    <title>{% trans "GakuNin RDM Admin | Delete banner" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Delete banner" %}
の2つのメッセージIDに分割することを提案します。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/banners/create.html
> +    <title>{% trans "GakuNin RDM Admin | Schedule banner" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Schedule banner" %}
の2つのメッセージIDに分割することを提案します。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/home.html
> +        <p>{% trans " Use the menu on the left to access admin pages. " %}</p>
メッセージIDを空白で開始/終端するのは事故の元なので外へ掃き出すことを推奨します。
` <p> {% trans "Use the menu on the left to access admin pages." %} </p>`

2020-03-11 09:52 UTC, hide24 commented on admin/templates/login.html
> +<title>{% trans "GakuNin RDM Admin | Log in" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Log in" %}
の2つに分割を提案

2020-03-11 09:52 UTC, hide24 commented on admin/templates/maintenance/display.html
>              <td>{{ current_alert.start }} - {{ current_alert.end }} UTC</td>
(メモ:とりあえず対処の必要ありません) エンドユーザーに対して表示されるメンテナンス時間の表示はlocal timeであるべきでは？
一段下の表示はlocal timeぽいので問題ない？

2020-03-11 09:52 UTC, hide24 commented on admin/templates/maintenance/display.html
> +                    {% trans "The site will undergo maintenance between &lt;localized start time&gt;-&lt;localized end time&gt;. Thank you for your patience." %}
`&lt;localized start time&gt;` つまり `<localized start time>` と
`&lt;localized end time&gt;` つまり `<localized end time>` はプログラム的に意味のある文字列で翻訳されたり別の文字列に変化すると困るので翻訳ファイルには出力されないようにしてください。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/meetings/create.html
> +    <title>{% trans "GakuNIn RDM Admin | Meetings" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Meetings" %}
の2つに分割を提案

2020-03-11 09:52 UTC, hide24 commented on admin/templates/meetings/detail.html
> +    <title>{% trans "GakuNin RDM Admin | Meetings" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Meetings" %}
の2つに分割を提案

2020-03-11 09:52 UTC, hide24 commented on admin/templates/meetings/list.html
> +    <title>{% trans "GakuNin RDM Admin | Meetings" %}</title>
{% trans "GakuNin RDM Admin"%} | {% trans "Meetings" %}
の2つに分割を提案

2020-03-11 09:52 UTC, hide24 commented on admin/templates/nodes/confirm_ham.html
> +        <h3>{% blocktrans %}Are you sure this {{ resource_type }} is {% endblocktrans %}<strong>{% trans "not" %}</strong>{% blocktrans %} spam? {{ guid }}{% endblocktrans %}</h3>
blocktrans はメッセージID部にhtmlタグを含むことができたような気がするけど駄目なんだっけ？
`<h3>{% blocktrans %}Are you sure this {{ resource_type }} is <strong>not</strong> spam? {{ guid }}{% endblocktrans %}</h3>`
では動作しない？

2020-03-11 09:52 UTC, hide24 commented on admin/templates/nodes/remove_contributor.html
> +        add them back.{% endblocktrans %}
(optional)本質的な問題ではありませんが、このような場所では{% blocktrans %} と {% endblocktrans %}を別の行にした方がdiffが見やすくなるのでお薦めです。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/osf/providerassetfile_confirm_delete.html
> +                        {% trans "Are you sure you want to delete " %}<b>{{ object.name }}</b>{% trans "?" %}
blocktrans を使用して
`{% blocktrans  %}Are you sure you want to delete <b>{{ object.name }}</b>?{% endblocktrans %}`
では駄目？

2020-03-11 09:52 UTC, hide24 commented on admin/templates/osf/providerassetfile_confirm_delete.html
> +    <title>{% trans "GakuNin RDM Admin | Delete Asset" %}</title>
{% trans "GakuNin RDM Admin" %} | {% trans "Delete Asset" %}
への分割を推奨

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_addons/addons/dataverse_credentials_modal.html
> +                                        {% blocktrans %}(Get from Dataverse <i class="fa fa-external-link-square"></i>){% endblocktrans %}
翻訳ファイルにあまりタグを露出させたくないのだけど
`({% trans "Get from Dataverse" %} <i class="fa fa-external-link-square"></i>)`
では駄目？

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_addons/addons/owncloud_credentials_modal.html
> +                                    <em>{% blocktrans %}Only ownCloud instances supporting <a href="https://doc.owncloud.org/server/9.1/user_manual/files/access_webdav.html" target="_blank">WebDAV</a
(あとで書く)

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_custom_storage_location/institutional_storage.html
>                      <input type="text" required class="form-control" id="storage_name" name="storage_name" value="{{ region.name }}" oninvalid="this.setCustomValidity('This field is required.') " oni
'This field is required.' と disabled は翻訳対象のはず

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_custom_storage_location/providers/nextcloud_modal.html
> +                                    <em>{% blocktrans %}Only Nextcloud instances supporting <a
(あとで書く)

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_custom_storage_location/providers/nextcloud_modal.html
>                                  <input type="text" class="form-control nextcloud-params" id="nextcloud_username" placeholder="username" required>
プレースホルダの'username'も翻訳することを推奨

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_custom_storage_location/providers/nextcloud_modal.html
> +                                <em>{% blocktrans %} These credentials will be encrypted. However, we <strong>strongly
(あとで書く)

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_custom_storage_location/providers/owncloud_modal.html
>                              <input required type="text" class="form-control owncloud-params" id="owncloud_username" placeholder="username">
プレースホルダの翻訳を推奨

2020-03-11 09:52 UTC, hide24 commented on admin/templates/rdm_statistics/settings.html
>  {% extends 'base.html' %}
(メモ) RDM Statisticsの階層にAnnouncementsの設定画面のテンプレートがある。怪しいので後で調べる

2020-03-11 09:52 UTC, hide24 commented on admin/templates/spam/email.html
> +    <p>{% trans "The GakuNin RDM Team" %}</p>
本来的にはif文の類いを全部前方に掃き出した上で判定結果を変数に代入
本文は全体を1つのblocktransで囲った上でif文の場所を変数へのバインディングにするべきです。
修正行数が多くなると思うので後日の修正でも良いです。

2020-03-11 09:52 UTC, hide24 commented on admin/templates/users/remove_2_factor.html
> +        {% trans "Removing this will let the user log in
blocktransを使用した方が良いです

2020-03-11 09:52 UTC, hide24 commented on framework/auth/oauth_scopes.py
> +                                    description='View all metadata, files, and access rights associated with all public and private projects accessible to this account.',
ここは翻訳されなくて良い？

2020-03-11 09:52 UTC, hide24 commented on framework/auth/oauth_scopes.py
>                                       description='View and edit all metadata, files, and access rights associated with '
ここは翻訳されなくて良い？

2020-03-11 09:52 UTC, hide24 commented on framework/auth/oauth_scopes.py
> +                           description=unicode(_('View all information associated with this account, including for private projects.')),
気持ちは判るけどさすがに冗長なので別の対処をすべき。
1行目(shebang)に`# coding: utf-8`とかやっても駄目？
あとこれでugettext_lazyは本当にlazyな評価がされている？

2020-03-11 09:52 UTC, hide24 commented on website/notifications/utils.py
>                  'help': 'These are settings for each of your projects. Modifying ' +
ここの翻訳は不要？

2020-03-11 09:52 UTC, hide24 commented on website/notifications/utils.py
> +                'title': unicode(_('Default Notification Settings')),
unicode()の使用に関して……

2020-03-11 09:52 UTC, hide24 commented on website/project/__init__.py
> +        title=unicode(_('Bookmarks')),
unicode()の使用に関して……

2020-03-11 09:52 UTC, hide24 commented on website/search/elastic_search.py
> +    'project': unicode(_('Projects')),
unicode()の使用に関して

2020-03-11 09:52 UTC, hide24 commented on website/static/js/accessRequestManager.js
> +            Raven.captureMessage(agh.sprintf(_('Could not %1$s access request'),trigger), {
バインドする変数が一つだけなら序数はつけない方が良い

2020-03-11 09:52 UTC, hide24 commented on website/static/js/accountClaimer.js
> +    $osf.growl(_('Email will arrive shortly'), [_('Please check <em>'), $osf.htmlEscape(email), '</em>'].join(''), 'success');
`['Please check <em>', $osf.htmlEscape(email), '</em>'].join('')`
については、sprintfフォーマットに翻訳してからgettextをあてる
`sprinft('Please check <em>%s</em>', $osf.htmlEscape(email))`
か、'Please check'に対して翻訳を抽出した方が良い

2020-03-11 09:52 UTC, hide24 commented on website/static/js/accountSettings.js
> +            $osf.growl('Error', _('Could not fetch user profile.'), 'danger');
現在のスタイルでは表示されていないけど、第1引数はダイアログのタイトルなので最初の'Error'は翻訳されるべき

2020-03-11 09:52 UTC, hide24 commented on website/static/js/accountSettings.js
> +                $osf.growl('Error', agh.sprintf(_('User profile not updated. Please refresh the page and try again or contact %1$s if the problem persists.'),$osf.osfSupportLink()), 'danger');
growlの第一引数……

2020-03-11 09:52 UTC, hide24 commented on website/static/js/accountSettings.js
> +                     _('will <strong>NOT</strong> be able to reactivate your account.'),
メッセージIDはできるだけ文の途中で分割されないようにする

2020-03-11 09:52 UTC, hide24 commented on website/static/js/addProjectPlugin.js
> +                                    placeholder : agh.sprintf(_('Enter %1$s description'),_(ctrl.nodeType))
引数の間の,の後に空白文字がないとLintで警告が出そう

2020-03-11 09:52 UTC, hide24 commented on website/static/js/addProjectPlugin.js
> +                                    _('structure in the new project without importing the content of that project.')),
メッセージIDが文中で分割されないように

2020-03-11 09:52 UTC, hide24 commented on website/static/js/rdmGettext.js
> +'use strict';
このファイルをrequireした各ファイルで
var rdmGettext = require('js/rdmGettext');
var gt = rdmGettext.rdmGettext();
var _ = function(msgid) { return gt.gettext(msgid); };
と同じ処理が記述されているのが冗長に感じる
こっちのファイルで _ のfunctionまで生成してexportした方が全体にスッキリしないかな？

2020-03-11 09:52 UTC, hide24 commented on website/templates/base.mako
> +            see our <a %(meatwiki_url)s>Privacy Policy</a>\
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/claim_account.mako
> +                    <label style="margin-right: 15px">${_('I have read and agree to the <a %(meatwiki_termsOfUse)s>Terms of Use</a> and <a %(meatwiki_privacyPolicy)s>Privacy Policy</a>.') % dict(meat
caseの▼統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/claim_account_registered.mako
> +                <a id="signOutLink" href='${signOutUrl}'>${_("I am <strong>not</strong> <em>%(user_fullname)s</em>.</a>") % dict(user_fullname=h(user.fullname)) | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/footer.mako
> +                        Copyright &copy; 2016-${datetime.utcnow().year}
この修正は込山先生の指示？

2020-03-11 09:52 UTC, hide24 commented on website/templates/footer.mako
> +                        ${_("Terms&nbsp;of&nbsp;Use") | n}
(メモ)本来的にはデザイン的な意図であるnbspが翻訳ファイルに露出するべきではない。
ただ、ここにnbspが置かれているという事は置かないと改行されるパターンがあった(画面幅が足りない場合のレスポンシブが適用された場合など？)ということで、ここからnbspを取り除くためにはスタイルシートの調整が必要になると思われる。
修正は保留が妥当か？

2020-03-11 09:52 UTC, hide24 commented on website/templates/include/profile/schools.mako
>                          <div class="row">
(メモ)年月日のセレクタの多言語化についてはフレームワーク側のサポートがあるはずなのでちゃんと調べる。
今回はこのままで

2020-03-11 09:52 UTC, hide24 commented on website/templates/util/render_node.mako
> +<!-- ${_("component")} -->
最新のdevelopブランチに対してrebaseしていますか？
html的にコメントアウトされているので表示は変化しないはずですが、

2020-03-11 09:52 UTC, hide24 commented on website/templates/util/render_node.mako
> +            <i class="fa fa-link" data-toggle="tooltip" title='${_("Linked %(node_type)s") % dict(node_type=_(summary['node_type']))}'></i>
極力行頭行末の空白文字の状態は変化させないようにしてください
メッセージID中のキーワードはcamelCaseで統一する

2020-03-11 09:52 UTC, hide24 commented on website/templates/messages.mako
> +${_("Duplicate template")}
ファイルの先頭にコメントとしてこのファイルが存在する意図を記述しておいてください。
あとファイル名についても検討した方が良いかも知れません。
本質的には「何かの辞書」であるはずなのでそうした意味を持つ名前にした方が良いです。

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile.mako
> +            <li><a href="#social" data-toggle="tab">${_("Social")}</a></li>
現在のdevelopと要素の並び順が異なります。
追従するようにしてください

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile.mako
> +
上記ナビリンクの並び順を変更した上で各タブの内容を保持しているdivタグの並び順を揃えてください。

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile.mako
> +<%include file="include/profile/social.mako" />
ここもタブの並び順変更の影響

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile.mako
> +          socialUrls: socialUrls,
タブの並び順変更の修正。実際のところここは直さなくても動作に影響ないけど直してください

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile/settings.mako
> +				<li><a href="#social" data-toggle="tab">${_("Social")}</a></li>
リンクの並び順が最新のdevelopと異なります。
追従してください。

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile/settings.mako
> +                </div>
タブの並び順の変更

2020-03-11 09:52 UTC, hide24 commented on website/templates/profile/settings.mako
> +<%include file="include/profile/social.mako" />
タブの並び順の変更

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/addon/page.mako
> +        ${_("%(full_name)s add-on is not configured properly.") % dict(full_name=full_name) | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/addon/page.mako
> +            ${_('Configure this add-on on the <a href=%(node_url)s>add-ons</a> page.') % dict(node_url='"' + h(node['url']) + 'addons/"') | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/addon/widget.mako
> +                ${_("%(full_name)s add-on is not configured properly.") % dict(full_name=full_name)}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/addon/widget.mako
> +                    ${_('Configure this add-on on the <a href=%(node_url)s>add-ons</a> page.') % dict(node_url='"' + h(node['url']) + 'addons/"') | n}
caseの統一

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/contributors.mako
>          <h3> Requests for Access</h3>
ここは訳さない？

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/modal_add_contributor.mako
> +                                            <a class="f-w-lg" data-bind="click: startSearchParent, text:'Import contributors from ' + parentTitle"></a>
空白文字を不必要に変更しないでください

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/modal_add_pointer.mako
> +                <!--    <li id="getLinksRegistrationsTab"><a data-bind="click: registrationView">Registrations</a></li>-->
この行のコメントアウトは誰の指示ですか？

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/project.mako
> +                                         <span %(text_customCitation)s></span>') % dict(f_x_xl='class="f-w-xl"',text_customCitation='data-bind="text: customCitation"') | n}
他のページに習うなら'Cite as:'だけをメッセージIDとして抽出すれば良いような気がします。

2020-03-11 09:52 UTC, hide24 commented on website/templates/project/project_header.mako
> +</div>
ファイル末尾には改行を打つ。既存ファイルの空白文字を特別な意図なく変更しない

2020-03-11 09:52 UTC, hide24 commented on website/templates/search.mako
> +            <h4><a data-bind="attr: {href: guid_url || deep_url}, text: name"></a> ${_('(<span %(is_retracted)s>Withdrawn </span><span %(is_registration)s>Registration </span>File)') % dict(is_retrac
キーワードis_retracted, is_registrationの命名について
これらはif式に与えられる判定用変数の名前なので、メッセージIDに出現するキーワードとしてはisではなくifの使用を提案します。
case問題とあわせてifRetracted, ifRegistrationを提案

2020-03-11 09:52 UTC, hide24 commented on website/templates/search.mako
> +        <p>${_('<strong>Jump to:</strong><!-- %(ifStart_n_wikis)s --><a %(wikiUrl)s>Wiki</a> -<!-- %(ifEnd)s --><a %(filesUrl)s>Files</a>') % dict(ifStart_n_wikis='ko if: n_wikis > 0',ifEnd='/ko',wik
knockoutのロジックそのものをメッセージIDに含めないでください。
この箇所については'Jump to:', 'Wiki', 'Files'の3つのメッセージIDが抽出されれば十分です。

2020-03-11 09:52 UTC, hide24 commented on website/templates/search.mako
> +        <p>${_('<strong>Jump to:</strong><!-- %(ifStart_n_wikis)s --><a %(wikiUrl)s>Wiki</a> -<!-- %(ifEnd)s --><a %(filesUrl)s>Files</a>') % dict(ifStart_n_wikis='ko if: n_wikis > 0',ifEnd='/ko',wik
前記と同様。元の記述に戻した上で'Jump to:', 'Wiki', 'Files'がメッセージIDとして抽出されるようにしてください。

2020-03-11 09:52 UTC, hide24 commented on website/templates/search_bar_help_modal.mako
> +                    ${_('<p>Search uses the <a %(xwiki)s>Lucene search syntax</a>.This gives you many options, but can be very simple as well. Examples of valid searches include:</p>') % dict(xwiki='
'xwiki'のキーワードについて'searchQuerySyntaxUrl'への変更を提案します。

2020-03-11 09:52 UTC, hide24 requested changes
総評としてはとても良い出来だと思います。
主な指摘内容としては、
・翻訳ファイル(potやpo)に出現するキーワード(変数名)のcaseについて
camelCaseとsnake_caseが混在しています。
主にhtmlのクラス名/IDやjavaScript中の変数名に由来するキーワードがcamelCase
python中の変数名に由来するキーワードがsnake_caseになっているという事情は理解できますが
翻訳ファイルを見る人には関係のない事情ですし、翻訳ファイルだけを見る人にはプロジェクトの統制が劣っているように見えてしまいます。
そのためどちらかに統一されるべきです。
既存の量的にcamelCaseの方が多いように感じるのでsnake_caseの箇所にコメントを入れています。(途中で飽きたので全部ではないです)
snake_caseの方が好みならそちらに統一しても良いです。
・JavaScript中でのgetText関連のrequire
各ファイルでgetText関連のライブラリをrequireする際に常に3行コピペされています。
rdmGettext.jsの側で_をexportしておけばrequrieの1行で足りると思います。
・JavaScript中でのsprintfライブラリの利用法について
`var sprintf = require('agh.sprintf').sprintf;`
とrequireすれば実際にsprintfを利用する際のagh.の接頭辞が不要になるはずです。
sprintfフォーマット中に置換される変数が1つしかない場合は序数を付与せず%sとした方が可読性が高いと思います。
また、agh.sprintfではなくnode.sprintfライブラリを利用すれば他の場所で利用しているような名前ベースの変数挿入ができるようです。
https://github.com/maritz/node-sprintf

2020-03-11 10:00 UTC, hide24 commented on website/templates/search.mako
> +            <h4><a data-bind="attr: {href: guid_url || deep_url}, text: name"></a> ${_('(<span %(is_retracted)s>Withdrawn </span><span %(is_registration)s>Registration </span>File)') % dict(is_retrac
冷静に考えたら条件分岐ロジックがメッセージID内に含まれるのはおかしいので、各部で切り分けて別々のメッセージIDとするべきか

2020-03-11 10:04 UTC, hide24 commented
以下の点は問題だと思うので優先的に修正してください。
後は金曜までに間に合う範囲で取捨選択に応じます。

website/templates/profile.makoで最新版ではタブの並び順が変更になっているのに追従できていない箇所
https://github.com/RCOSDP/RDM-osf.io/pull/154#discussion_r390817049 ほか

knockoutの条件分岐をメッセージIDに含めてしまっている箇所
https://github.com/RCOSDP/RDM-osf.io/pull/154#discussion_r390841727
https://github.com/RCOSDP/RDM-osf.io/pull/154#discussion_r390842920

2020-03-13 10:14 UTC, hide24 commented
修正ありがとう。
動作を見ていて気付きましたが
https://github.com/RCOSDP/RDM-osf.io/blob/feature/i18nJS-202001-n2/website/language.py
のファイルも翻訳が必要なようです。とり急ぎ連絡だけです。

2020-03-17 02:12 UTC, hide24 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
typo: s/nstitution.name/institution.name/

2020-03-17 02:15 UTC, hide24 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
typo: s/nstitution.name/institution.name/

2020-03-17 05:45 UTC, west1636 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
該当するコードを修正しました。

2020-03-17 06:04 UTC, hide24 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
https://github.com/RCOSDP/RDM-osf.io/blob/feature/i18nJS-202001-n2/admin/templates/institutions/node_list.html
当該のファイルの最終の状態はこれだと思うけど、直ってる？

2020-03-17 06:13 UTC, west1636 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
Yesです。修正されています。line14行目を修正しました。

2020-03-17 07:27 UTC, hide24 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
14行目にtypoがあるんじゃないかと思うのだけど、ちゃんとinstitution.nameに直っていますか?

2020-03-18 02:46 UTC, west1636 commented on admin/templates/institutions/node_list.html
> +    <h2>{% blocktrans with institutionName=nstitution.name %}List of Nodes for {{ institutionName }}{% endblocktrans %}
失礼しましました。typoを修正しました。

2020-03-24 02:15 UTC, hide24 approved these changes
残件の修正は別途行う

2020-03-24 02:47 UTC, merged