Feature/attiribute entitlement administrator
RCOSDP/RDM-osf.io pull request #19
Opened 2018-11-04 22:57 UTC by rdm-dev03

https://github.com/RCOSDP/RDM-osf.io/pull/18 でご指摘いただいた内容
・不要なデコレータの削除
・不要クラスの削除
を行いましたので、改めてPRを送信させていただきます。

2018-11-15 00:04 UTC, NII-RCOSDP commented on addons/base/views.py
> +#    return result
L895にreturnを移動させ、エラー処理後の最後のreturn行をコメントアウトしているのはなぜでしょうか。
返り値として何を期待しているのか読み取りにくい気がします。

2018-11-15 10:29 UTC, NII-RCOSDP requested changes
メールの送信部分など、コメントアウトが戻ってしまっていたりJavaScriptの変更分が含まれていないなど、マージ作業に負荷がかかりそうなので、このPRを取り下げ、再度一連の変更が揃った状態でPRを出してください。

よろしくお願いいたします

2018-11-15 10:29 UTC, NII-RCOSDP commented on admin/rdm_addons/oauth/views.py
>          """権限等のチェック"""
[imo] コメント関係は英語で

2018-11-15 10:29 UTC, NII-RCOSDP commented on admin/rdm_statistics/views.py
> +#        connection.send_messages([message])
6401にて802行目のコメントアウトを外す指定がありますが、803行目ではないでしょうか？。
また、コメントアウトの修正が反映されていないようです。

2018-11-15 10:29 UTC, NII-RCOSDP commented on admin/rdm_statistics/views.py
>              'test': 'test',
この行は必要でしょうか？

2018-11-15 10:29 UTC, NII-RCOSDP commented on admin/templates/login.html
> +                    </div>
これは不要ではないか

2018-11-15 10:29 UTC, NII-RCOSDP commented on root_cert_verifycate.pem
> +-----BEGIN CERTIFICATE-----
これは公開すべきファイルではないと思います。

2018-11-15 10:29 UTC, NII-RCOSDP commented on website/oauth/views.py
> +def osfadmin_oauth_calback(service_name):
osfadmin_oauth_calback => osfadmin_oauth_callback

2018-11-15 10:52 UTC, ghost requested changes
RCOSDPで書き込んでしまいました。
現在のPRを取り下げ、修正をあげ直してください。

2018-11-16 01:11 UTC, hide24 requested changes
コメント化されたコードの削除が十分ではありません
メール送信まわりの修正がデグレードを起こしているようです

2018-11-16 01:17 UTC, rdm-dev03 commented on root_cert_verifycate.pem
> +-----BEGIN CERTIFICATE-----
このファイルは、タイムスタンプの検証処理で利用するファイルです。
./api/base/settings/defaults.py の VERIFY_ROOT_CERTIFICATE で指定しているファイルで、
このファイルを用いてverifyを実施しますが、TravisCIでのテスト時にこのファイルが存在しないとエラーとなるため同梱しています。
ファイルは
http://eswg.jnsa.org/sandbox/handson/  で証明書ファイル として今回されているものになります。

2018-11-16 02:53 UTC, rcos-kouno commented on root_cert_verifycate.pem
> +-----BEGIN CERTIFICATE-----
公開されているものとして承知いたしました。

ご確認ありがとうございます。

2018-11-16 06:01 UTC, rdm-dev03 commented
ご指示に従いPRを取り下げます。

2018-11-16 06:01 UTC, closed without merging