#23498 ストレージクオータの表示部修正
RCOSDP/RDM-osf.io pull request #222
Opened 2021-03-11 00:54 UTC by ivis-wangzg

## Purpose

#23498 ストレージクオータの表示部修正

## Changes

RDM-osf.io/admin/institutions/views.py
RDM-osf.io/admin/templates/institutions/statistical_status_default_storage_user.html

2021-03-15 00:43 UTC, hide24 requested changes

2021-03-15 00:43 UTC, hide24 commented on admin/templates/institutions/statistical_status_default_storage_user.html
> +                {% trans "eduPersonPrincipleName" %}
対応する言語リソースの追加が必要かと思います。
西川さんに手順を確認してください。

2021-03-15 00:43 UTC, hide24 commented on tests/base.py
> +            self.context.push()
この変更の意図は何でしょうか?

2021-03-15 04:52 UTC, ivis-wangzg commented on tests/base.py
> +            self.context.push()
変更不要です。申し訳ございません、元に戻りました

2021-03-15 04:54 UTC, ivis-wangzg commented on admin/templates/institutions/statistical_status_default_storage_user.html
> +                {% trans "eduPersonPrincipleName" %}
日本名「利用者ID」を言語リソースに追加いたしました。

2021-03-23 04:33 UTC, hide24 approved these changes

2021-04-02 08:28 UTC, fujimotodaisuke commented
CONFLICT が発生し TravisCI でもエラーが発生しているためマージできません。
修正をお願いします。

2021-04-22 06:02 UTC, ivis-miyazawa commented
@fujimotodaisuke 
修正しました。
マージお願いします。

2021-04-26 03:57 UTC, merged