Hotfix/6898,6901
RCOSDP/RDM-osf.io pull request #23
Opened 2018-12-04 10:11 UTC by rdm-dev03

管理者機能によるメール送信機能からの送信時の設定パラメタ追加、および
Adminページログイン時の所属機関再設定

GRDM-6898でご指摘いただいた、「shibboleth loginにおいて認可を与えている機関のものではない管理画面にアクセスできる」件、および
GRDM-6901でご指摘いただいた「管理者機能によるメール送信機能でのメールの FROM 欄を
現状の実装の SUPPORT_EMAIL以外への変更」 について対応させていただきました。

各々の修正ですが、
GRDM-6898
https://github.com/RCOSDP/RDM-osf.io/commit/6e572f7dbecc5e44ad337884f7d77a372a7d8045

GRDM-6901
https://github.com/RCOSDP/RDM-osf.io/commit/5bcec4b19d5954d97fccce7c1f40d0a7aa732d6d
https://github.com/RCOSDP/RDM-osf.io/commit/8eac159c0dc2582ffa5f2656e1ca80041750cab7
の修正となります。
https://redmine.devops.rcos.nii.ac.jp/issues/6901#note-3 の
ご指摘

> 不特定多数(now_user.username)をSESに登録するのは現実的ではないです。

を鑑み、FROMメールからnow_user.username をいったん削除いたしました。

 ## Purpose

 - 1. add parameter 'ANNOUNCEMENT_EMAIL_FROM' when sending mail from rdm_annoucement.
 - 2. reassign affiliated institution id when user logs in to admin page

## Changes
  - admin/base/settings/defaults.py
 - admin/rdm_announcement/views.py
   add parameter 'ANNOUNCEMENT_EMAIL_FROM'

 - admin/common_auth/views.py
   reassign affiliated institution when log in to Admin, and user already exists.

  ## QA Notes
 - None

 ## Side Effects
 - None

## Ticket
- GRDM-6898, GRDM-6901

2018-12-06 06:26 UTC, ghost reviewed
GRDM-6898
吉本の指示の通りとなっているとしてApproveします。

GRDM-6901
ANNOUNCEMENT_EMAIL_FROMを追加し別途指定できる形になっているのでApproveします。

2018-12-06 06:37 UTC, hide24 requested changes

2018-12-06 06:37 UTC, hide24 commented on admin/common_auth/views.py
> +            eppn_user.affiliated_institutions.add(institution)
指摘の意図は意図しない組織を取り除くことなのでaddでは駄目です。
institution以外を明示的にremoveするか、institutionのみの状態でsetしてください。

2018-12-06 08:16 UTC, rdm-dev03 commented on admin/common_auth/views.py
> +            eppn_user.affiliated_institutions.add(institution)
昨日の藤本様の修正
https://github.com/RCOSDP/RDM-osf.io/compare/0b33453b3017...873ec27df08c
と同じく、今のinsutitution以外を削除、再設定する(removeしてadd)と
して修正いたします。

2018-12-06 12:19 UTC, rdm-dev03 commented
https://github.com/RCOSDP/RDM-osf.io/commit/2f4bd91851fe89ce332843b4887f9429eac21862 
として修正いたしました。

2018-12-07 08:36 UTC, hide24 approved these changes

2018-12-07 09:22 UTC, ghost commented
日立さんありがとうございます。
創夢さん、こちらでマージを開始してください。また、stg2へのデプロイもお願いいたします。

2018-12-12 02:09 UTC, ghost approved these changes
ありがとうございます。
マージさせていただきます。

2018-12-13 01:56 UTC, merged