Feature/202210 institutional storage control/fixedbug/39836_note-18
RCOSDP/RDM-osf.io pull request #441
Opened 2023-11-29 06:59 UTC by ndnhat1

## Purpose

Relate to the following issue:
[NII Redmine#39836]エクスポート開始後、プロセスのステータスが"Pending"となり、エクスポート処理が開始されない
- Create a new File Info JSON with full data including failed files when exporting data.
- Add a function to check files exist on the Export storage location when clicking [Check Export data] button.

## Changes

No DB changes

## QA Notes

## Documentation

## Side Effects

## Ticket

2023-12-04 02:03 UTC, hide24 requested changes
コメントを確認ください。

2023-12-04 02:03 UTC, hide24 commented on admin/rdm_custom_storage_location/export_data/views/export.py
> +            raise ExportDataTaskException(MSG_EXPORT_FAILED_UPLOAD_TO_LOCATION)
末端まで確認できていないので見当違いのことを言っているかも知れませんが、
S3互換の機関ストレージ、または現状のActiveScale(S3互換)をバックエンドとするNII Storageにおいては
プロジェクトから辿った複数のfile nodeが指し示すストレージ上のファイルの実体が、同じファイルを差している場合があります。
(同じ内容のファイルを別のファイル名でアップロードした場合など)
そうした場合に、アップロード処理は新規追加ではなく更新として処理されることになるはずです。
レスポンスコードが204(No Content)でも正常な場合はあるような気がします。

2023-12-06 09:47 UTC, hidefumi-moritani commented on admin/rdm_custom_storage_location/export_data/views/export.py
> +            raise ExportDataTaskException(MSG_EXPORT_FAILED_UPLOAD_TO_LOCATION)
コメントありがとうございます。

詳細は別途回答させていただきますが、
レスポンスコードが 204(No Content) の場合も、
正常応答として扱うロジックに変更させていただきます。

2023-12-08 00:32 UTC, hide24 approved these changes

2023-12-11 00:26 UTC, merged