Feature/202210 user management/4.2
RCOSDP/RDM-osf.io pull request #445
Opened 2023-12-18 12:14 UTC by tma-ntphat

## Purpose
(2)4.2.機関登録ユーザ情報一覧を取得する機能
It includes the features of (2)4.1.管理者機能でのユーザの識別情報、利用状況表示機能: view list of all user identification information (only ones of the institution for institutional admin), and view user details.
And add the following features:

- Search users by GUID, username, and fullname
- Sort on column fields (exclude GUID)
- Export the user list to CSV

*Note: This pull request is affected by pull request #444. So must pull before this pull request.

## Changes

 Implement the new features

## QA Notes

- Data migration: None

2024-01-04 05:07 UTC, hide24 requested changes

2024-01-04 05:07 UTC, hide24 commented on admin/user_identification_information/utils.py
> +            continue
この対応表がここに埋まっているのはメンテナンス性が悪いと思います。
きっと、アドオンの追加時に修正が漏れて後々悩むことになります。
もっとアドオンに近い場所に移すべきです。
意味的には各アドオンが自身の属性として知っておくべき情報ですが、修正箇所がやたら増えるので、
addons.json に対応表を置くのがリーズナブルかと思います。

2024-03-18 11:25 UTC, hidefumi-moritani commented on admin/user_identification_information/utils.py
> +            continue
コメントありがとうございます。

> 意味的には各アドオンが自身の属性として知っておくべき情報ですが、修正箇所がやたら増えるので、
> addons.json に対応表を置くのがリーズナブルかと思います。

addons.json に下記の定義を追加することを考えています。念の為、認識違いがないかご確認をお願いします。

```
diff --git a/addons.json b/addons.json
--- a/addons.json	(revision 127ed0287560ae3e46424ee267bd491da6f2a8bb)
+++ b/addons.json	(date 1710757326280)
@@ -182,5 +182,28 @@
         "s3",
         "s3compat",
         "owncloud"
-    ]
+    ],
+    "addons_folder_field": {
+        "s3": "folder_name",
+        "s3compat": "folder_name",
+        "s3compatb3": "folder_name",
+        "azureblobstorage": "folder_name",
+        "box": "folder_name",
+        "figshare": "folder_name",
+        "onedrivebusiness": "folder_name",
+        "swift": "folder_name",
+        "bitbucket": "repo",
+        "github": "repo",
+        "gitlab": "repo",
+        "googledrive": "folder_path",
+        "iqbrims": "folder_path",
+        "onedrive": "folder_path",
+        "dropbox": "folder",
+        "weko": "index_title",
+        "mendeley": "list_id",
+        "zotero": "list_id",
+        "owncloud": "folder_id",
+        "nextcloud": "folder_id",
+        "dataverse": "dataverse"
+    }
 }
```

2024-03-29 00:45 UTC, hidefumi-moritani commented on admin/user_identification_information/utils.py
> +            continue
修正が完了しましたので、ご確認よろしくお願いします。

2024-06-12 05:08 UTC, hide24 approved these changes

2024-10-07 03:14 UTC, merged