Feature/202210 institutional storage control/fixedbug/37211
RCOSDP/RDM-osf.io pull request #460
Opened 2024-03-07 04:56 UTC by tma-ntphat

\* Re-create this pull request for the old one https://github.com/RCOSDP/RDM-osf.io/pull/448

## Purpose

Support Export / Restore on institutional storage (Add-on method)

## Changes
Support export/restore institutional storage (add-on method) and fix issues related to institutional storage (Add-on method)
## Documentation

None

## Side Effects

None

## Ticket

[Bug][NII Redmine#37211]機関ストレージ(アドオン方式)におけるエクスポート・リストア処理の残課題について
[Bug][NII Redmine#36941]リストア後にファイル作成者が変更される
[Bug][NII Redmine#36122]空のフォルダのエクスポート
[Bug][NII Redmine#36934]エクスポートデータ一覧/エクスポート元ストレージの名称が変化する

2024-06-12 05:18 UTC, hide24 requested changes
大筋に異論はありませんが、テストクラスにコンフリクトがあるようです。
確認ください。

2024-06-12 05:18 UTC, hide24 commented on admin_tests/rdm_custom_storage_location/export_data/test_utils.py
developの最近とコンフリクトがあるようです。

2024-07-04 00:57 UTC, hidefumi-moritani commented on admin_tests/rdm_custom_storage_location/export_data/test_utils.py
コンフリクトを解消しました。ご確認よろしくお願いします。

2024-08-04 11:28 UTC, hide24 approved these changes

2025-10-22 08:24 UTC, merged