WIki機能の改修
RCOSDP/RDM-osf.io pull request #461
Opened 2024-03-07 07:55 UTC by west1636

## Purpose

・ページ階層化機能
・Wikiインポート機能
・ページ階層編集機能

## Changes
・Wikiアドオンの改修(addons/wiki/)
・elsticsearchのタイムアウト値の変更(website/settings/defaults.py)、bulk_update_wikiの改修
・webpack.common.config.jsの改修
・wiki-page.cssの改修

2024-03-26 09:39 UTC, hide24 requested changes
`addons/wiki/views.py` については後で追記します。
ひとまずそれ以外。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/exceptions.py
> +class ImportTaskAborted(WikiError):
Exceptionクラス(それもWikiErrorを継承したもの)のsuffixがAbortedで終わっているのは正しい命名ですか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +    def save(self, wiki_import=False, *args, **kwargs):
`wiki_import`引数の名称に違和感があります。
`save`メソッド内においては「検索インデックスの更新のスキップ」を要求する引数なのだから、そうした意図の汲める名称であるべきです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +    def create_for_node(self, node, name, content, auth, parent=None, wiki_import=False):
`wiki_import`引数の名称に違和感があります。
状態を表わすboolean引数は`is_`, `in_`,`for_`等の接頭辞が欲しいです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +        wiki_page.update(auth.user, content, wiki_import)
呼び出し時のシグネチャとしてキーワード引数として利用する方針に決めたなら全域でキーワード引数として扱うべきです。
混在させると引数の追加を伴う次回の更新時にバグを生みやすいです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +                return None
戻り値が配列である場合と`None`である場合が混在するのは呼び出し側が混乱しませんか?
実際`None`が戻る場合を考慮できていない呼び出し元があるように散見されます。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +    def create(self, wiki_import=False, **kwargs):
`wiki_import`の名称、状態を表わすbooleanなのだから`is_`, `in_`,`for_`等の接頭辞が欲しい。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +    def save(self, wiki_import=False, *args, **kwargs):
`wiki_import`の名称

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +    def update(self, user, content, wiki_import=False):
`wiki_import`の名称

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/models.py
> +        version.save(wiki_import)
キーワード引数表記を希望します。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tasks.py
> +    'run_project_wiki_validate_import',
`validate` と `import` と動詞が二つ並ぶと何が起きるか想像できないので、`validate_for_import`等何か接続詞を挿入してください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tasks.py
> +            wiki_pages.append(wiki_page)
技法の話としては
`wiki_pages = [WikiPage.objects.get(id=wiki_id) for wiki_id in wiki_id_list if wiki_id]`
とかの方がpythonらしくて好きです。

それはそれとして、これらの記述だとwiki_id_listの行数回のSQLが発行されるので、
`wiki_pages = WikiPage.objects.filter(id__in=wiki_id_list)`
するのが良さそうな気がしますが、それでは不味い理由がありますか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tasks.py
> +def create_wiki_pages(wiki_id_list):
このメソッドは`create`なのだろうか?
あと可視性はpublicで良い? privateメソッドであった方が良かったりはしませんか?
ページの所有権の確認が行われていないので、外部から呼ばれると意図しないページが取得できてしまう場合がありそうです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/abort_wiki_import.mako
> +    async function intervalGetAbortWikiImportResult(url, ms, timeout, operation) {
引数`ms`の命名が適切でないように見えます。意味の判る名前を付けてください。
おそらくポーリングのインターバルの類いのように見えます。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/abort_wiki_import.mako
> +        var timeoutCtn = timeout * 1000 / ms
インターバルと閾値で別の単位を利用するのは混乱を招きませんか?
また、端数が出る場合に`timeout`引数より短かい時間で終了するのも気になります。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/add_wiki_page.mako
> +                    </div>
`same`というwiki名のページが存在した場合に破綻しそうですが、大丈夫でしょうか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/add_wiki_page.mako
> +                    window.location.href = ${ urls['web']['base'] | sjson, n } + encodeURIComponent(wikiName);
新規ページが表示された際のステートの話だと思いますが、あらかじめ編集モードにしておくことはできない?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/add_wiki_page.mako
> +                    }
質問です。
この処理で拾われるエラーを引き起こすようなデータはどのような原因で作成されると考えていますか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +        <div class="panel-toggle col-sm-${'3' if 'menu' in panels_used else '1'}" style="width: 26%">
検証していませんが、直感的に colクラスを使用した横幅指定(可変)とstyleで直書きされているwidthの横幅指定が競合しそうに見えます。
ブラウザの互換性試験は万全なのでしょうか?

値を固定したいのであればcolクラスの可変部を固定することを推奨します。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +    <div class="panel-expand col-sm-${'9' if 'menu' in panels_used else '11'}" style="width: 74%">
検証していませんが、直感的に colクラスを使用した横幅指定(可変)とstyleで直書きされているwidthの横幅指定が競合しそうに見えます。
ブラウザの互換性試験は万全なのでしょうか?

値を固定したいのであればcolクラスの可変部を固定することを推奨します。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +                        <div class="col-sm-8" style="width:100%">
colクラスとstyleでのwidth直書きの併用は止めてください。
bootstrap由来のレイアウトシステムに悪影響を及ぼします。
col-4クラスを持つdiv削除したのであれば、残されたdivのcolを12にしてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +                                <div class="pull-right" style="margin-left: 20px;>
マージン制御にはbootstrap由来のmarginクラスを使用してください。
他にどうしようもない場合以外で、style属性を付与しないでください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
>                        % else:
可能なかぎり、style属性の直書きは避けてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +                                      >Finish</button>
多言語化対応していないのはわざとですか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +                                    value="Save"
多言語化対応していないのはわざとですか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +        <div><p style="display: inline-block; margin-right: 12px;">title:</p><input id="linkTitle" class="form-control" type="text" style="display: inline-block; width: 75%;" placeholder="Enter the T
bootstrap由来のレイアウトシステムを使用してください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +        <div><p style="display: inline-block; margin-right: 19px;">alt:</p><input id="imageAlt" class="form-control" type="text" style="display: inline-block; width: 75%;" placeholder="Enter the URL"
bootstarp由来のレイアウトシステムを利用してください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/edit.mako
> +            sharejs: ${ sharejs_url | sjson, n },
`sharejs_url` とこのファイルの下部にある`sharejs_url`からのファイルの取り寄せは今でも必要なのですか?

2024-03-26 09:39 UTC, hide24 commented on website/static/css/pages/wiki-page.css
行頭のスペースの数は揃えてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +                    <p id="attentionValidateInfo" class="partOperationAll" style="display: none">
類似点多数：
今回は修正は求めないことにしますが、原則としてコンポーネントの表示/非表示の制御をdisplay属性で行う実装は非推奨です。
ビューのテストの自動化の際に格段に手間数が増えます。覚えておいてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +                      <div style="display: inline-block; margin-right: 10px;"><input name="importOperation" type="radio" id="createNewAll" value="createNewAll"/><label for="createNewAll">Create New A
レイアウトはbootstrapのレイアウトシステムを利用するようにしてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +            const validateImportTask = await requestValidateImportTask(validateImportUrl, $alertInfoForm, $submitForm);
参考情報として、requestValidateImportTaskの想定処理時間を教えてください。
想定される最頻値と最大の処理時間が知りたいです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +        function fixToImportList(operation, validateImportResultCopy, perOperationList) {
関数の名前から処理内容が想像できません。おそらく名前が適切でないです。
一般論として、引数のオブジェクトに破壊的な変更を及ぼす関数は設計に誤りがある場合が多いです。
おそらく、やりたいことはArrayのフィルタリングであるように見えるので、Array.filterなどを用いるべきだと思います。
実装方針の変更を強く推奨します。
最低でもこの関数の意図と作用についてのコメントを足してください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +            }
`validateImportResult`が偽である場合はスルーして良いのでしょうか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/templates/import_wiki_page.mako
> +<!-- New Component Modal -->
このファイル内で使用されているシンボルの命名規則について
似たような語感で`import_wiki`と`wiki_import`など同じキーワードを含有して語順が異なる、
あるいは`import_wiki`と`import`でwikiの単語が落ちているものなどが散見されます。
特に意図が無いのであれば、こうしたブレは避けてください。
意図があるなら、それを明示するようにしてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_no_parent(self):
メソッド名に含まれる`no`が何のことなのか判りません。
不正な値の検査であれば、`invalid`や`nonexistent`等が適切ではないでしょうか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_no_parent_home(self):
やはり`no`が何のことやら判らないので名前の再検討を。
あと`home`のキーワードも判りにくいので、デフォルトで作成される`ホーム`ページの話であればそれと知れるもう少し説明的な名前が良いです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_parent_home(self):
`home`について〜

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> -    def test_read_only_users_cannot_view_edit_pane(self):
パネルの構成変更によるテストの廃止はともかく、同様に書き込み権限の有無によるコンポーネントの差異についてのテストは要らないのでしょうか?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +        assert_equal(parent_wiki.deleted, None)
アセットの状態を一々確認する必要はありません。
設定条件を明記したいならコメントを付けるか、より判りやすい変数名を用いた方が良いです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +
Flake8等に文句を言われないように空白行の入れすぎには注意。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_delete_hierarchy(self, mock_shrejs):
メソッド名に違和感があります。名称の再検討を推奨します。
「子を持つノードが削除された場合の挙動」のテストだと思われますが、そうしたニュアンスが伝わりません。
「親殺し」か「再帰的削除」あたりが適切なキーワードだと思います。
あと、テストケースとしては2階層以上の再帰が欲しいです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> -from future.moves.urllib.parse import quote
極力無意味なdiffが発生しないように気をつけてください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def get_node_guid(node):
nodeオブジェクトのインスタンスからguidのidを引くのでは不味い理由があるのでしょうか?
また`_prefetched_objects_cache`に求める値がキャッシュされている保証はありますか?
とても用途が限定される実装になっていて、メソッド名からそれが推測できない名前になっているので、
名前か実装、どちらかが適切でないように見えます。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def get_all_wiki_name_import_directory(dir_id):
とても効率が悪い実装になっているので、実装方針の再考してください。
特に全てのwikiページがpythonのオブジェクトとしてメモリ上に展開されるのは最悪です。
`only`等の利用を検討してください。
また戻り値も2つの配列の並び順が重要ならnameをkeyにしたdictである方が良いと思います。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def _get_all_child_directory(dir_id):
` get_all_wiki_name_import_directory(dir_id)` と同様の問題があります。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def get_wiki_directory(wiki_name, dir_id):
メソッド名と挙動が一致していないように見えます。名称の再検討を推奨します。
また、実装もかなりあやうい上に計算量が無駄に多いです。
指定のwiki名から親のidを順に遡って、指定のディレクトリのidに合致することがあるかどうかを検査すれば
最大でもディレクトリの階層回のSQLの発行で収まるはずです。
実装方針を再考してください。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +        parent_wiki_page = WikiPage.objects.get(id=wiki.parent)
modelにリレーションを張っておいたら?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def get_wiki_numbering(node, w_name):
メソッド名が適切ではありません。「既存wiki名に連番を付与して新しい名前を得る」意図の判る名前にしてください。
あとSQLの発行数が多くなりすぎるので実装を再検討してください。
重複が判明した後は`filter(name__startswith=w_name)`とかで、like検索してからnameを加工するのが良いのではないですかね?

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def get_max_depth(wiki_info):
不明なオブジェクトを引数にするのは止めてください。
あとおそらく何かのリストのようなので引数のシグネチャは`wiki_infos`等複数形であるべきです。
単一責務の原則からすると、おそらくはここにあるべきメソッドではありません。
あと、`max`関数は`sort`関数を引数に取ることができるので`for`を使う必要は無いはずです。(計算量が減ります)

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def create_import_error_list(wiki_info, imported_list):
これもおそらくは`get_max_depth`と同様にここにあるべきメソッドではないのだと思います。
`wiki_info(s)`というリストの管理と整形メソッドを備えたクラスがあるべきなのではないでしょうか?
せめて、`wiki_info(s)`というリストを作成するのと同じファイルに移動するべきです。
おそらく`views.py`

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +    if node.id != node_id:
`node_id`という汎用的な名前の変数に代入すると色々情報が失われるので、`if`の評価式中で直接参照した方が良いです。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def check_dir_id(dir_id, node):
このメソッドの主眼は何ですか? 名前から想像できません。
名前が適切でないのだと思います。
実装に関しても、引数の`node`がファイルノードかどうかの判定なら`isinstance()`あるいは`type()`関数で評価した方が計算量が安いし、意図も伝わりやすいと思います。

2024-03-26 09:39 UTC, hide24 commented on addons/wiki/utils.py
> +def extract_err_msg(err):
繰り返しになりますが、他のオブジェクトの内部構造に詳しいメソッドはそのオブジェクトが定義された場所の近くにあるべきです。

2024-03-26 09:39 UTC, hide24 commented on tests/test_webtests.py
> +        #assert_in(wiki_content, res)
これはどういう意図ですか?

2024-03-26 09:39 UTC, hide24 commented on website/search/elastic_search.py
> +        return helpers.bulk(client(), actions, chunk_size=1)
意図が判りません。どのようなメリットを狙って`chunk_size`を変更したのか説明をください。
一般的にはパフォーマンスが低下するだけのように思うのですが。(もはやbulkの意味がない)

2024-03-26 09:39 UTC, hide24 commented on website/settings/defaults.py
> +ELASTIC_TIMEOUT = 60
ちょっと長過ぎる気がします。
本当に長時間待つ必要があるインポート処理とその他で基準値を分割できませんか?

2024-04-08 01:55 UTC, hide24 commented on addons/wiki/views.py
ユーティリティとして括り出されているメソッドからの引数や戻り値にwikiページオブジェクトの配列を受け渡すのは止めてください。
ORMのカーソル、参照に必要なインデックス情報、実際に最低限必要なカラムの内容(これはトータルのサイズによる)
など必要最低限の情報のみが引き渡されるようにしてください。
all_children_obj とか言われるとメモリ消費量が心配すぎます。

2024-04-11 08:41 UTC, west1636 commented on addons/wiki/exceptions.py
> +class ImportTaskAborted(WikiError):
ImportTaskAbortedErrorへ変更。

2024-04-11 08:41 UTC, west1636 commented on addons/wiki/models.py
> +    def save(self, wiki_import=False, *args, **kwargs):
is_wiki_importへ変更

2024-04-11 08:41 UTC, west1636 commented on addons/wiki/models.py
> +    def create_for_node(self, node, name, content, auth, parent=None, wiki_import=False):
is_wiki_importへ変更

2024-04-11 08:43 UTC, west1636 commented on addons/wiki/utils.py
> +def check_dir_id(dir_id, node):
check_file_object_in_nodeへ変更

2024-04-11 08:44 UTC, west1636 commented on addons/wiki/utils.py
> +def extract_err_msg(err):
views.pyへ移動

2024-04-11 08:46 UTC, west1636 commented on addons/wiki/models.py
> +    def create(self, wiki_import=False, **kwargs):
is_wiki_importへ変更

2024-04-11 08:46 UTC, west1636 commented on addons/wiki/models.py
> +    def save(self, wiki_import=False, *args, **kwargs):
is_wiki_importへ変更

2024-04-11 08:46 UTC, west1636 commented on addons/wiki/models.py
> +    def update(self, user, content, wiki_import=False):
is_wiki_importへ変更

2024-04-11 08:46 UTC, west1636 commented on addons/wiki/models.py
> +        version.save(wiki_import)
キーワード引数表記へ変更

2024-04-11 08:46 UTC, west1636 commented on addons/wiki/models.py
> +        wiki_page.update(auth.user, content, wiki_import)
キーワード引数表記へ変更

2024-04-11 08:47 UTC, west1636 commented on addons/wiki/tasks.py
> +    'run_project_wiki_validate_import',
run_project_wiki_validate_for_importへ変更

2024-04-11 08:48 UTC, west1636 commented on addons/wiki/tasks.py
> +            wiki_pages.append(wiki_page)
`wiki_pages = WikiPage.objects.filter(id__in=wiki_id_list)` へ改修

2024-04-11 08:49 UTC, west1636 commented on addons/wiki/templates/abort_wiki_import.mako
> +    async function intervalGetAbortWikiImportResult(url, ms, timeout, operation) {
interval_msへ変更

2024-04-11 08:50 UTC, west1636 commented on addons/wiki/templates/abort_wiki_import.mako
> +        var timeoutCtn = timeout * 1000 / ms
timeoutの単位をmilisecond(timeout_ms)へ変更

2024-04-11 08:51 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +        <div class="panel-toggle col-sm-${'3' if 'menu' in panels_used else '1'}" style="width: 26%">
col4へ変更

2024-04-11 08:52 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +    <div class="panel-expand col-sm-${'9' if 'menu' in panels_used else '11'}" style="width: 74%">
col8へ変更

2024-04-11 08:52 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +                        <div class="col-sm-8" style="width:100%">
col12へ変更

2024-04-11 08:52 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +                                <div class="pull-right" style="margin-left: 20px;>
style属性を除外

2024-04-11 08:53 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +                                      >Finish</button>
多言語化対応漏れ修正

2024-04-11 08:53 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +                                    value="Save"
多言語化対応漏れ修正

2024-04-11 08:54 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +        <div><p style="display: inline-block; margin-right: 12px;">title:</p><input id="linkTitle" class="form-control" type="text" style="display: inline-block; width: 75%;" placeholder="Enter the T
極力boostrap由来のレイアウトを使用するよう変更

2024-04-11 08:55 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +        <div><p style="display: inline-block; margin-right: 19px;">alt:</p><input id="imageAlt" class="form-control" type="text" style="display: inline-block; width: 75%;" placeholder="Enter the URL"
極力boostrap由来のレイアウトを使用するよう変更

2024-04-11 08:55 UTC, west1636 commented on addons/wiki/templates/edit.mako
> +            sharejs: ${ sharejs_url | sjson, n },
指摘箇所不要のため、削除

2024-04-11 08:58 UTC, west1636 commented on addons/wiki/utils.py
> +def get_all_wiki_name_import_directory(dir_id):
以下の観点で修正
・あらかじめ計算結果をキャッシュしておく。
・レコード数を縮める。
・レコードのいらないカラムは取得しない

2024-04-11 08:58 UTC, west1636 commented on addons/wiki/utils.py
> +def _get_all_child_directory(dir_id):
以下の観点で修正
・あらかじめ計算結果をキャッシュしておく。
・レコード数を縮める。
・レコードのいらないカラムは取得しない

2024-04-11 08:58 UTC, west1636 commented on addons/wiki/utils.py
> +def get_wiki_directory(wiki_name, dir_id):
不要のため削除

2024-04-11 08:59 UTC, west1636 commented on addons/wiki/utils.py
> +def get_wiki_numbering(node, w_name):
・get_numbered_name_for_existing_wikiへ変更。
・`filter(name__startswith=w_name)` を使用。

2024-04-11 09:00 UTC, west1636 commented on addons/wiki/utils.py
> +def create_import_error_list(wiki_info, imported_list):
views.pyへ移動

2024-04-11 09:01 UTC, west1636 commented on addons/wiki/utils.py
> +    if node.id != node_id:
`if node.id != target.target_object_id:` に修正

2024-04-12 00:50 UTC, hide24 commented on addons/wiki/models.py
> +        wiki_page.update(auth.user, content, wiki_import)
コメントと修正内容が一致していないようです。

2024-04-12 09:27 UTC, west1636 commented on tests/test_webtests.py
> +        #assert_in(wiki_content, res)
新しいエディタはレスポンスを受け取った後、非同期で作成されるためresにwiki_contentは含まれません。
そのため該当箇所をコメントアウトしました。

2024-04-15 08:43 UTC, west1636 commented on addons/wiki/templates/add_wiki_page.mako
> +                    }
子ページを追加している間に別ブラウザで親ページが削除された場合、当該エラーが表示されます。

2024-04-16 12:45 UTC, west1636 commented on addons/wiki/models.py
> +                return None
get_for_nodeをget_for_child_nodesへ分割

2024-04-16 12:46 UTC, west1636 commented on addons/wiki/tasks.py
> +def create_wiki_pages(wiki_id_list):
_get_wiki_pages_by_idsへ変更

2024-04-16 12:49 UTC, west1636 commented on addons/wiki/templates/add_wiki_page.mako
> +                    </div>
valueをfalseへ変更し、親階層を別にhiddenで追加し値を取得するよう修正

2024-04-16 12:50 UTC, west1636 commented on addons/wiki/templates/add_wiki_page.mako
> +                    window.location.href = ${ urls['web']['base'] | sjson, n } + encodeURIComponent(wikiName);
新規ページ作成後、previewモードになるよう変更。編集ボタンを押下することで編集モードになります。

2024-04-16 12:51 UTC, west1636 commented on addons/wiki/templates/edit.mako
>                        % else:
一部のstyle属性をcssへ移動

2024-04-16 12:52 UTC, west1636 commented on addons/wiki/templates/import_wiki_page.mako
> +                      <div style="display: inline-block; margin-right: 10px;"><input name="importOperation" type="radio" id="createNewAll" value="createNewAll"/><label for="createNewAll">Create New A
極力boostrap由来のレイアウトを使用するよう変更

2024-04-16 12:54 UTC, west1636 commented on addons/wiki/templates/import_wiki_page.mako
> +        function fixToImportList(operation, validateImportResultCopy, perOperationList) {
・メソッド名をmodifyImportListへ変更。
・Array.filterを用いる実装に変更。
・関数の説明コメントを追加。

2024-04-16 12:56 UTC, west1636 commented on addons/wiki/templates/import_wiki_page.mako
> +            }
intervalGetCelerytaskResultにtimeout時の処理を追加。

2024-04-16 12:57 UTC, west1636 commented on addons/wiki/templates/import_wiki_page.mako
> +<!-- New Component Modal -->
語順をwikiImportに統一。

2024-04-16 12:59 UTC, west1636 commented on addons/wiki/utils.py
> -from future.moves.urllib.parse import quote
変更を元に戻しました。

2024-04-16 12:59 UTC, west1636 commented on addons/wiki/utils.py
> +def get_node_guid(node):
nodeオブジェクトのインスタンスからguidのidを引くよう修正。

2024-04-16 13:00 UTC, west1636 commented on addons/wiki/utils.py
> +        parent_wiki_page = WikiPage.objects.get(id=wiki.parent)
parentをIntergerから自身の外部キーに変更し、wikiオブジェクトから親ページ名を取得するよう修正。

2024-04-16 13:03 UTC, west1636 commented on addons/wiki/utils.py
> +def get_max_depth(wiki_info):
メソッドの目的、引数の説明を追加。また、maxの引数をジェネレータを使うよう修正。

2024-04-16 13:08 UTC, west1636 commented on website/search/elastic_search.py
> +        return helpers.bulk(client(), actions, chunk_size=1)
タイムアウト対策を目的としています。このメソッドはwiki専用なので、この設定を維持する方針です。

2024-04-16 13:15 UTC, west1636 commented on addons/wiki/templates/import_wiki_page.mako
> +            const validateImportTask = await requestValidateImportTask(validateImportUrl, $alertInfoForm, $submitForm);
2000ページ、一階層で120秒。
移行最大値は1683ページ、添付ファイル19359個、階層の深さは情報なしです。

2024-04-17 02:20 UTC, west1636 commented on addons/wiki/models.py
> +        wiki_page.update(auth.user, content, wiki_import)
変更を反映しました。

2024-04-18 00:44 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_no_parent(self):
test_project_wiki_validate_name_invalid_parentへ変更。

2024-04-18 00:44 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_no_parent_home(self):
test_project_wiki_validate_name_invalid_parent_default_homeへ変更。

2024-04-18 00:45 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_validate_name_parent_home(self):
test_project_wiki_validate_name_parent_default_homeへ変更。

2024-04-18 00:47 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> -    def test_read_only_users_cannot_view_edit_pane(self):
test_read_only_users_cannot_view_edit_pane廃止をやめ、
編集ボタン、共同編集のステータスのコンポーネントの表示の確認に変更。

2024-04-18 00:47 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +        assert_equal(parent_wiki.deleted, None)
当該コードを除外。

2024-04-18 00:47 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +
空白行を除外。

2024-04-18 00:48 UTC, west1636 commented on addons/wiki/tests/test_wiki.py
> +    def test_project_wiki_delete_hierarchy(self, mock_shrejs):
test_project_wiki_delete_recursive_one_levelへ変更。また、２層のテストケース(test_project_wiki_delete_recursive_two_level)を追加。

2024-04-22 07:35 UTC, west1636 commented on website/settings/defaults.py
> +ELASTIC_TIMEOUT = 60
Wikiのbulk処理のtimeout値を個別に設定するために、
別のElasticsearchクライアント（client_for_wiki_import）を定義しました。

2024-04-26 06:30 UTC, hide24 requested changes

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/models.py
> +    def create(self, wiki_import=False, **kwargs):
変更されていないようです。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/models.py
> +    def save(self, wiki_import=False, *args, **kwargs):
変更されていないようです。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/models.py
> +    def update(self, user, content, wiki_import=False):
変更されていないようです。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/clean_celery_tasks/'
見おとしていたけど、`clean_celery_tasks`というページが作成された場合に
`'/project/<pid>/wiki/<wname>/'` のルールと衝突します。
エンドポイントを変更してください。
一般的にはこうしたまぎらわしいルールを作成するべきではありません。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/get_abort_wiki_import_result/'
これも1つ上のコメントと同様`get_abort_wiki_import_result`というページが存在した場合に破綻します。
エンドポイントを変更してください。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/update_wiki_page_sort/'
これも同様、エンドポイントを変更してください。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/tasks.py
> +    return wiki_pages
ただ1箇所からしか呼ばれない1行のためにメソッド分割を行うのはいかがなものかと思います。
どのような意図なのでしょうか?

一般的にメソッド呼び出しはそれなりにコストがかかるので、呼び出しもとで同様の処理を行うべきだと思います。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/templates/abort_wiki_import.mako
> +        });
今更で悪いのだけど、ここで`$.ajax`をawaitするのではなく、わざわざ1段`Promise`でラップしている意図は何でしょう?

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/templates/abort_wiki_import.mako
> +                }, interval_ms);
この実装だと、APIアクセスの後、常に`interval_ms`待つことになりませんか?
終了判定が来た際には速やかに次の処理へ進みたくありませんか?
あと、ここも`$.ajax`に`.done`を書いて`$.ajax`をawaitした方が見通しが良くなると思います。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/utils.py
> -from future.moves.urllib.parse import quote
`from future.moves.urllib.parse import quote` の一行は以前はこのファイルの7行目にあったものが3行目に移動されているように見えます。
できれば、こういうのは止めて欲しいのです。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/utils.py
> +        yield from _get_all_child_file_ids(child_folder._id)
以前よりは多少マシですが、意図がまったく伝わっていないようなので、具体的なコードを書くと
```
children_file_ids = list(BaseFileNode.objects.filter(parent_id=dir_id, type='osf.osfstoragefile', deleted__isnull=True).values_list(_id,  flat=True))
children_folder_ids = list(BaseFileNode.objects.filter(parent_id=dir_id, type='osf.osfstoragefolder', deleted__isnull=True).values_list(_id,  flat=True))
```
の後`children_folder_ids`について再帰的な処理が実行されることを期待します。
`_id`のリストが欲しいだけなのに、全件をpythonオブジェクトに変換しないでください。

あと、typeは`osfstorage`決め打ちで良いんだっけ?

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/utils.py
> +    node_file_infos = BaseFileNode.objects.filter(target_object_id=node.id, type='osf.osfstoragefile', deleted__isnull=True).values_list('_id', 'name', 'parent_id__name')
ここは`values_list`より`values`の方が、次の行の可視性が上がるはずです。(dictっぽいオブジェクトが帰るので)

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/utils.py
> +    return import_wiki_name_list
ちゃんと読み取れているか自身が無いのですが、この`wiki_info`は`in`でループさせているが1レコードしか無いということで良いのでしょうか?
そうであればループの記述は取り除いてください。
そうでないのであれば、メモリ占有量に対する懸念に対処できていないように思います。
どうなんでしょうか?

プロダクションコードは書くのにかけた時間の数倍の時間をかけて読みとかれるものです。
とにかく読みやすい記述を心掛けてください。

2024-04-26 06:30 UTC, hide24 commented on addons/wiki/utils.py
> +    existing_wikis = WikiPage.objects.filter(page_name__istartswith=base_name, deleted__isnull=True, node=node)
必要なカラムは`page_name`だけのように見えるので、`values` `values_list`等の利用を検討してください。

2024-05-16 05:46 UTC, west1636 commented on addons/wiki/utils.py
> +    existing_wikis = WikiPage.objects.filter(page_name__istartswith=base_name, deleted__isnull=True, node=node)
values_listを利用するよう修正。

2024-05-16 05:48 UTC, west1636 commented on addons/wiki/utils.py
> +    return import_wiki_name_list
wiki_infoはインポートする全てのWikiページの種々の情報が格納されます。現状維持としました。

2024-05-16 05:50 UTC, west1636 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/clean_celery_tasks/'
エンドポイントをclean_clelery_tasks→tasks/clean変更しました。

2024-05-16 05:50 UTC, west1636 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/get_abort_wiki_import_result/'
エンドポイントをget_abort_wiki_import_result→abort/result/へ変更しました。

2024-05-16 05:50 UTC, west1636 commented on addons/wiki/routes.py
> +            '/project/<pid>/node/<nid>/wiki/update_wiki_page_sort/'
エンドポイントをupdate_wiki_page_sort →sort/update/へ変更しました。

2024-05-16 05:51 UTC, west1636 commented on addons/wiki/tasks.py
> +    return wiki_pages
メソッド分割をやめ、run_update_search_and_bulk_indexメソッド内に組み込みました。

2024-05-16 05:52 UTC, west1636 commented on addons/wiki/templates/abort_wiki_import.mako
> +        });
await $.ajaxだと期待した動作が得られなかったため、ラップしました。

2024-05-16 05:52 UTC, west1636 commented on addons/wiki/templates/abort_wiki_import.mako
> +                }, interval_ms);
終了判定が来た際には速やかに次の処理へ進むようにコードを改修。

2024-05-17 00:19 UTC, west1636 commented on addons/wiki/utils.py
> +        yield from _get_all_child_file_ids(child_folder._id)
修正しました。
typeについては機関ストレージインポートの改修時、修正が入る可能性があります。

2024-10-22 13:47 UTC, hide24 commented on tests/test_webtests.py
> +        #assert_in(wiki_content, res)
不要なコードであれば削除してください。

2025-09-10 00:28 UTC, closed without merging