hotfix/10845
RCOSDP/RDM-osf.io pull request #83
Opened 2019-05-08 06:23 UTC by rdm-dev02

## Purpose
・verify_user および verify_date がNULL時の対策
・ファイル出力時に未定項目のIDやラベルはUnknownで構成

## Changes
## QA Notes
## Side Effects
## Ticket

GRDM#10845

2019-05-08 10:57 UTC, hide24 commented on website/static/js/pages/timestamp-common.js
> +            timestampId: 'https://rdf.rdm.nii.ac.jp/resource/ts/' + item.project_id + '/' + item.file_id + '/' + userId + '/' + tsDate,
今回の更新に関わる場所ではありませんが、"rdf.rdm.nii.ac.jp"のFQDNはリソース化されるべきです

2019-05-08 10:57 UTC, hide24 commented on website/static/js/pages/timestamp-common.js
>              orgNameResource: item.organization_name ? 'https://rdf.rdm.nii.ac.jp/resource/org/' + item.organization_name.replace(/ /g, '_') : null,
これも今回の更新に関わる場所ではありませんが、item.organization_nameからエスケープされる必要のある
(名前に含まれる可能性のあるURLに使用できない)文字は%20(' ')だけなのでしょうか？
他にも類似のエスケープ処理が数か所あるようです。

2019-05-08 10:57 UTC, hide24 commented on website/templates/project/timestamp.mako
> +                                    <td class="verify_user_name_id">${ 'Unknown' if not error_info['verify_user_id'] else '{} ({})'.format(error_info['verify_user_name'], error_info['verify_user_id']
特別なそうすべき理由が無い限りにおいて、else句を含む条件式は正論理で記述されるべきだと考えます。

2019-05-09 02:12 UTC, rdm-dev08 commented on website/templates/project/timestamp.mako
> +                                    <td class="verify_user_name_id">${ 'Unknown' if not error_info['verify_user_id'] else '{} ({})'.format(error_info['verify_user_name'], error_info['verify_user_id']
条件（ `if not error_info['verify_user_id']` ）がすぐ見れる為、一番短い値（ `'Unknown'` ）を先にしましたね。これで値は二つの形があるとすぐ分かります。

パフォーマンスに影響はないし、どの順番にするかそれはあくまでも開発者のスタイルによってですね。

どうしても
```python
'{} ({})'.format(error_info['verify_user_name'], error_info['verify_user_id']) if error_info['verify_user_id'] else 'Unknown'
```
というスタイルに合わせたいなら、もちろんできます。

2019-05-09 02:31 UTC, hide24 commented on website/templates/project/timestamp.mako
> +                                    <td class="verify_user_name_id">${ 'Unknown' if not error_info['verify_user_id'] else '{} ({})'.format(error_info['verify_user_name'], error_info['verify_user_id']
変更をお願いします

2019-05-10 01:50 UTC, rdm-dev08 commented on website/static/js/pages/timestamp-common.js
>              orgNameResource: item.organization_name ? 'https://rdf.rdm.nii.ac.jp/resource/org/' + item.organization_name.replace(/ /g, '_') : null,
Javascriptの `escape()` と `encodeURI()` と `encodeURIComponent()` という関数がこの場合に役に立つと思います。
https://stackoverflow.com/questions/332872/encode-url-in-javascript
https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent

`escape()` は使わない方が良いらしいです。 `@*/+` 文字はエンコードしません。
`encodeURI()` はURL全体をエンコードします。 `~!@#$&*()=:/,;?+'` 文字はエンコードしません。
`encodeURIComponent()` は一つのパラメターをエンコードします。 `~!*()'` 文字はエンコードしません。

```javascript
// encodeURI
var organizationName = 'Waseda University';
encodeURI('https://rdf.rdm.nii.ac.jp/resource/org/' + organizationName);
"https://rdf.rdm.nii.ac.jp/resource/org/Waseda%20University"

organizationName = '早稲田大学';
encodeURI('https://rdf.rdm.nii.ac.jp/resource/org/' + organizationName);
"https://rdf.rdm.nii.ac.jp/resource/org/%E6%97%A9%E7%A8%B2%E7%94%B0%E5%A4%A7%E5%AD%A6"
```

```javascript
// encodeURIComponent
var organizationName = 'Waseda University';
'https://rdf.rdm.nii.ac.jp/resource/org/' + encodeURIComponent(organizationName);
"https://rdf.rdm.nii.ac.jp/resource/org/Waseda%20University"

organizationName = '早稲田大学';
'https://rdf.rdm.nii.ac.jp/resource/org/' + encodeURIComponent(organizationName);
"https://rdf.rdm.nii.ac.jp/resource/org/%E6%97%A9%E7%A8%B2%E7%94%B0%E5%A4%A7%E5%AD%A6"
```

`encodeURI()` と `encodeURIComponent()` 両方使えると思いますが、`encodeURI()` のう方がエンコードしない文字がありますね。
機関名だけおエンコードしたいなら、 `encodeURIComponent()` の方が無難だと思います。

2019-05-10 02:27 UTC, rdm-dev08 commented on website/static/js/pages/timestamp-common.js
> +            timestampId: 'https://rdf.rdm.nii.ac.jp/resource/ts/' + item.project_id + '/' + item.file_id + '/' + userId + '/' + tsDate,
そのURLを変数にしました。 https://github.com/RCOSDP/RDM-osf.io/pull/83/commits/3df7a5780f4c100f4c4f60910d4a28f7e0c7e28d

2019-05-10 02:38 UTC, rdm-dev08 commented on website/static/js/pages/timestamp-common.js
>              orgNameResource: item.organization_name ? 'https://rdf.rdm.nii.ac.jp/resource/org/' + item.organization_name.replace(/ /g, '_') : null,
ファイル名、ユーザ名、機関名を `encodeURIComponent` でエンコードするようにした。 46380c905294c5e6e1c983a363634109874043eb

2019-05-10 02:39 UTC, rdm-dev08 commented on website/templates/project/timestamp.mako
> +                                    <td class="verify_user_name_id">${ 'Unknown' if not error_info['verify_user_id'] else '{} ({})'.format(error_info['verify_user_name'], error_info['verify_user_id']
変更しました。 4e201227c2ba197d412b9ea4353e373d48e661d6

2019-05-10 06:56 UTC, hide24 requested changes
RESOURCE_URL の変数名を再検討してください
それ以外は問題ありません

2019-05-10 06:56 UTC, hide24 commented on website/static/js/pages/timestamp-common.js
> +var RESOURCE_URL = 'rdf.rdm.nii.ac.jp';
FQDNはそれ自体ではURLではないので変数名の RESOURCE_URL  は適切でないと考えます。
URLの語彙的には RESOURCE_HOST ぐらいを推奨します。

2019-05-13 01:22 UTC, rdm-dev08 commented on website/static/js/pages/timestamp-common.js
> +var RESOURCE_URL = 'rdf.rdm.nii.ac.jp';
承知 68ff4f098619b5a1eb03162b533b7770cdec5e5d

2019-05-13 02:25 UTC, hide24 approved these changes

2019-05-13 02:25 UTC, merged