Hotfix/10639
RCOSDP/RDM-osf.io pull request #84
Opened 2019-05-08 08:27 UTC by rdm-dev02

## Purpose

・timestamp adding failed when filename with white space
・Bug fix: basefilenode is created when there is no record whose "path"value matches "path" instead of "materialized_path" value

## Changes
## QA Notes
## Side Effects
## Ticket
　GRDM#10639

2019-05-09 03:09 UTC, hide24 commented
障害の原因の理解については間違いないと思いますが、技巧的に過ぎる解決法だと感じます。
シェル文字列をシェルの文法に則って分割したいという状況については
shlex.split 関数が用意されているのでこちらを利用するべきだと考えます。

SSL_CREATE_TIMESTAMP_REQUEST = 'openssl ts -query -data {0} -cert -sha512'
等のテンプレート文字列において、変数の挿入箇所をエスケープした上で
SSL_CREATE_TIMESTAMP_REQUEST = 'openssl ts -query -data "{0}" -cert -sha512'
shlex.split 関数に食わせれば良いのではないでしょうか？

2019-05-09 04:08 UTC, hide24 requested changes
コメントを参照ください

2019-05-10 08:34 UTC, rdm-dev03 commented
ご指示いただいた、shlex.split を用いるように修正しました。

> SSL_CREATE_TIMESTAMP_REQUEST = 'openssl ts -query -data {0} -cert -sha512'
> 等のテンプレート文字列において、変数の挿入箇所をエスケープした上で
>SSL_CREATE_TIMESTAMP_REQUEST = 'openssl ts -query -data "{0}" -cert -sha512'

タイムスタンプトークンの実行コマンドは環境によってlocal.pyで書き換えられることが想定されますので、
ファイル名を渡す部分（上記では{0}） を 「"」でエスケープする（してあるはず）、という想定だと、付記漏れによる誤動作 が考えられるため実施処理でエスケープするようにしています。
( https://github.com/RCOSDP/RDM-osf.io/pull/84/commits/8cdb5a89246b69e03178dde7b3bd093b15064d8a#L499 )

2019-05-10 08:50 UTC, hide24 commented
ありがとうございます。
UPKIのTSAを利用する際のコマンドのテンプレート文字列は更新不要ということで良いですか？

2019-05-10 08:50 UTC, hide24 approved these changes

2019-05-10 09:34 UTC, rdm-dev03 commented
以前、小川より送付させていただいた、UPKI関連の機微な情報について.txt記載の 変数、
UPKI_CREATE_TIMESTAMP、UPKI_VERIFY_TIMESTAMP から変更はございません。

2019-05-10 10:01 UTC, merged