Hotfix/10038
RCOSDP/RDM-osf.io pull request #85
Opened 2019-05-08 11:35 UTC by rdm-dev02

## Purpose
Width fix for pagination

## Changes
## QA Notes
## Side Effects
## Ticket
　GRDM#10038

2019-05-09 02:18 UTC, hide24 requested changes

2019-05-09 02:18 UTC, hide24 commented on website/static/css/pages/timestamp-page.css
> +    /* width: 42px; */
もともとのwidthの意図としては、頻繁に目にするであろう1～2桁のページインデックスの見た目を揃える事だったのではないかと推察します。
widthを単に削除するよりはmin-widthに変更した方が本来の意図に近い表示になるように思います。
また、削除する場合はちゃんと行削除をしてください。

2019-05-10 08:28 UTC, rdm-dev02 commented on website/static/css/pages/timestamp-page.css
> +    /* width: 42px; */
ご確認ありがとうございます。
ご指摘の通り、見た目を揃えることが意図でしたので、
widthの削除ではなく、min-widthに変更いたしました。
また、行削除いたしました。

2019-05-10 08:52 UTC, hide24 approved these changes

2019-05-10 08:52 UTC, merged