Hotfix/10682
RCOSDP/RDM-osf.io pull request #91
Opened 2019-05-14 01:21 UTC by rdm-dev02

## Purpose
TimestampContorol画面のファイルリストの表示時刻修正

## Changes
## QA Notes
## Side Effects
## Ticket
　GRDM#10682

2019-05-14 02:45 UTC, hide24 requested changes
TravisCIでエラーが報告されています
確認をお願いします。

2019-05-14 02:45 UTC, hide24 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
関数名に"to UTC"とありますが、処理内容はUTCからlocaltimeへの変換です。
関数名が適切ではありません。
また、入力がUTCである確証がありません。
極端な話、postgreSQLの設定が変更されると表示がズレます。
ちゃんとtimezoneが保持できている層で変換すべきです。

2019-05-15 07:09 UTC, rdm-dev02 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
TravisCIエラーを解消いたしました。
ご指摘の通り、関数名が不適切でしたので"datesToLocal()"に修正いたしました。
なお、他のWeb側画面(Filesなど)の時刻表記と合うような対応を取っております。
（時刻表記についてAdmin側含めいくつかの画面を調べましたが、
　統一はされていないようでした。）

2019-05-16 07:33 UTC, hide24 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
ごめんなさい、参考にされた箇所というのが良くわからなかったので、どこのことか具体的に情報をいただけますか？
ざっと検索したところでは最終的に表示されているtext文字列をDateとしてパースして再加している処理はここ以外に見つけられませんでした。
属性値として保持している値をパースしているケースはいくつか見つかりました。

本質的に /website/util/timestamp.py で
・strftimeする前にlocaltimeに変換するか
・timezone情報を含む文字列に変換した上で(現在と同様に)表示された文字列をlocaltimeに変換する
のが妥当だと考えます。(前者を推奨)

2019-05-17 06:46 UTC, rdm-dev02 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
FormattableDate()を使用しているかについてgrep確認しておりました。
（抜粋）
website/static/js/components/autocomplete.js:137:
        var dateUpdated = new $osf.FormattableDate(item.value.dateUpdated);
website/static/js/components/autocomplete.js:138:
        var dateInitiated = new $osf.FormattableDate(item.value.dateInitiated);
website/static/js/components/logFeed.js:61:
                    log.attributes.formattableDate = new $osf.FormattableDate(log.attributes.date);
website/static/js/conference.js:75:
                        var dateCreated = new osfHelpers.FormattableDate(item.data.dateCreated);
website/static/js/filepage/revisions.js:196:
        revision.date = new $osf.FormattableDate(revision.modified_utc);
website/static/js/myProjects.js:347:
    item.date = new $osf.FormattableDate(item.attributes.date_modified);
website/static/js/myProjects.js:471:
                    log.attributes.formattableDate = new $osf.FormattableDate(log.attributes.date);
website/static/js/nodeControl.js:31:
    self.dateCreated = new $osf.FormattableDate(data.node.date_created);
website/static/js/nodeControl.js:32:
    self.dateModified = new $osf.FormattableDate(data.node.date_modified);
website/static/js/nodeControl.js:33:
    self.dateForked = new $osf.FormattableDate(data.node.forked_date);
website/static/js/nodeControl.js:38:
    self.dateRegistered = new $osf.FormattableDate(data.node.registered_date);
website/static/js/nodeControl.js:39:
    self.dateRetracted = new $osf.FormattableDate(data.node.date_retracted);


推奨案としてあげてくださった
　・strftimeする前にlocaltimeに変換する
ということは、クライアント側では変換せず、サーバ側の時刻を表示する
ということになりますでしょうか？（そうするとズレたままになりませんでしょうか。）

2019-05-17 09:20 UTC, hide24 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
いずれも、表示用にフォーマットされた文字列という訳ではないように見えます。

> そうするとズレたままになりませんでしょうか。
コンテナ内でtimezoneの設定はしていないのでしたっけ？
となると、B案のstrftimeの出力にtimezone情報を含める方針になりますでしょうか。

2019-05-31 09:18 UTC, rdm-dev02 commented on website/static/js/pages/timestamp-page.js
> +function datesToUTC() {
PythonからJSに渡す時刻情報に、timezone情報を含めるように修正いたしました。
ご確認お願いいたします。

2019-06-03 06:30 UTC, hide24 commented on website/util/timestamp.py
> +            verify_date = data.verify_date.strftime('%Y/%m/%d %H:%M:%S z')
verify_date = data.verify_date.strftime('%Y/%m/%d %H:%M:%S%z')
では?

2019-06-04 01:57 UTC, rdm-dev02 commented on website/util/timestamp.py
> +            verify_date = data.verify_date.strftime('%Y/%m/%d %H:%M:%S z')
ご指摘恐れ入ります。%付きに修正いたしました。

2019-06-06 04:59 UTC, hide24 commented
timestamp error画面が2ページ以上にページングされる場合、2ページ目以降の時刻表示が期待どおりの動作をしていないように見えます。
JSによる補正が行なわれず、python側の出力ままになっている。
確認ください。

2019-06-07 06:18 UTC, merged